'use strict';
const fs=require('node:fs'),path=require('node:path');
module.exports=function createMedia(root){const tracks=JSON.parse(fs.readFileSync(path.join(root,'music/tracks.json'),'utf8'));const files=new Map(tracks.map(t=>[t.url,path.join(root,'music',t.id+'.mp3')]));return function serve(req,res,pathname){
 if(['/cosmetics-ui.js','/cosmetics-ui.css'].includes(pathname)||/^\/cosmetics\/(icons|pins)\/[a-z0-9_]+\.webp$/.test(pathname)){
  if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);res.end();return true;}
  const file=path.join(root,pathname.slice(1));if(!fs.existsSync(file)){res.writeHead(404);res.end();return true;}
  res.writeHead(200,{'Content-Type':pathname.endsWith('.webp')?'image/webp':pathname.endsWith('.css')?'text/css; charset=utf-8':'application/javascript; charset=utf-8','Content-Length':fs.statSync(file).size,'Cache-Control':pathname.endsWith('.webp')?'public, max-age=86400':'no-cache','X-Content-Type-Options':'nosniff'});if(req.method==='HEAD')res.end();else fs.createReadStream(file).pipe(res);return true;
 }
 if(pathname==='/android/Lil_Ago_Arena-Android-v1.apk'){if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);res.end();return true;}const file=path.join(root,'downloads/Lil_Ago_Arena-Android-v1.apk');res.writeHead(200,{'Content-Type':'application/vnd.android.package-archive','Content-Disposition':'attachment; filename="Lil_Ago_Arena-Android-v1.apk"','Content-Length':fs.statSync(file).size,'Cache-Control':'no-cache','X-Content-Type-Options':'nosniff'});if(req.method==='HEAD')res.end();else fs.createReadStream(file).pipe(res);return true;}
 if(pathname==='/lobby-music.js'||pathname==='/music/tracks.json'){if(!['GET','HEAD'].includes(req.method))return false;const file=path.join(root,pathname.slice(1));res.writeHead(200,{'Content-Type':pathname.endsWith('.js')?'application/javascript; charset=utf-8':'application/json; charset=utf-8','Cache-Control':'no-cache'});if(req.method==='HEAD')res.end();else fs.createReadStream(file).pipe(res);return true;}
 if(!pathname.startsWith('/music/'))return false;if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);res.end();return true}const file=files.get(pathname);if(!file){res.writeHead(404);res.end();return true}const size=fs.statSync(file).size;let start=0,end=size-1,status=200;const range=req.headers.range;if(range){const match=/^bytes=(\d*)-(\d*)$/.exec(range);if(!match||(!match[1]&&!match[2])){res.writeHead(416,{'Content-Range':'bytes */'+size});res.end();return true}if(!match[1])start=Math.max(0,size-Number(match[2]));else{start=Number(match[1]);if(match[2])end=Math.min(size-1,Number(match[2]))}if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start>=size||start>end){res.writeHead(416,{'Content-Range':'bytes */'+size});res.end();return true}status=206;}
 const headers={'Content-Type':'audio/mpeg','Content-Length':end-start+1,'Accept-Ranges':'bytes','Cache-Control':'public, max-age=86400','X-Content-Type-Options':'nosniff'};if(status===206)headers['Content-Range']=`bytes ${start}-${end}/${size}`;res.writeHead(status,headers);if(req.method==='HEAD')res.end();else{const stream=fs.createReadStream(file,{start,end});stream.on('error',()=>res.destroy());res.on('close',()=>stream.destroy());stream.pipe(res)}return true;
}}
