// Random team and four-player modes share the existing battle renderer and controls.
const multiplayerLabels={duo:'2대2',trio:'3대3',royale4:'4인 배틀로얄'};
let multiplayerToken=0;
const multiplayerBaseHome=home;
home=function(){multiplayerToken++;app.multiLobby=null;app.multiMode=null;app.multiSelected=null;app.multiAngle=0;app.multiIntroUntil=0;multiplayerBaseHome();const options=$('.modeOptions');if(!options)return;for(const [mode,label] of Object.entries(multiplayerLabels)){const b=document.createElement('button');b.className='modeChip'+(selectedLobbyMode===mode?' selected':'');b.dataset.modeSelect=mode;b.innerHTML='<span>'+(mode==='royale4'?'👑':'🛡️')+'</span>'+label;options.append(b);b.onclick=()=>{selectedLobbyMode=mode;options.querySelectorAll('[data-mode-select]').forEach(x=>x.classList.toggle('selected',x===b));$('#privateRoom').hidden=true;};}for(const id of ['random','duo','trio','royale4','private','royale','cpu','local']){const chip=options.querySelector('[data-mode-select=\"'+id+'\"]');if(chip)options.append(chip);}const one=options.querySelector('[data-mode-select=\"random\"]'),friendly=options.querySelector('[data-mode-select=\"royale\"]');if(one)one.innerHTML='<span>⚔️</span>1대1 랜덤';if(friendly)friendly.innerHTML='<span>👑</span>친구 로얄';const play=$('#playLobby'),normal=play.onclick;play.onclick=()=>multiplayerLabels[selectedLobbyMode]?startOnline(selectedLobbyMode):normal();};
const multiplayerBaseStart=startOnline;
// The header was bound before home was wrapped; resolve the current handler on click.
$('#goHome').onclick=()=>home();
const multiplayerBaseWaiting=waiting;
waiting=function(message,eyebrow='온라인 대기'){multiplayerBaseWaiting(message,eyebrow);if(app.online&&app.mode==='random'&&['온라인 연결','랜덤 매칭'].includes(eyebrow)){overlayContent.insertAdjacentHTML('beforeend','<button class="action alt" id="oneCancelQueue">매칭 취소</button>');$('#oneCancelQueue').onclick=()=>home();}};
startOnline=function(type,code=''){if(!multiplayerLabels[type])return multiplayerBaseStart(type,code);multiplayerBaseStart('random');app.mode=type;app.multiMode=type;app.pendingAction={action:'multi_queue',mode:type};};
function multiplayerError(e){const el=$('#multiError');if(el)el.textContent=e.message;else toastNotice(e.message);}
function multiplayerLobby(){const r=app.multiLobby;if(!r)return;const me=r.players.find(p=>p.sid===app.session),team=me?.team,offer=(app.multiOffer||[]).filter(id=>HM[id]);if(!offer.includes(app.multiSelected))app.multiSelected=me?.hero||offer[0];
 const people=(list)=>list.map(p=>'<div class="socialRow"><img style="width:40px;height:40px;object-fit:contain" src="'+playerImg(p)+'"><span><b>'+escapeHTML(p.nick)+'</b><small>🏆 '+(p.totalTrophies||0)+(p.sid===app.session?' · 나':'')+'</small></span><small>'+(p.ready?'✅ 준비':'선택 중')+'</small></div>').join('');
 const roster=team===null?people(r.players):'<h3 style="color:#48baff">🛡️ 우리 팀</h3>'+people(r.players.filter(p=>p.team===team))+'<h3 style="color:#ff7585">⚔️ 상대 팀</h3>'+people(r.players.filter(p=>p.team!==team));
 display('<div class="eyebrow">랜덤 매칭 · '+escapeHTML(r.label)+'</div><h2>캐릭터 선택</h2><p>'+(team===null?'순위 보상 · 🏆 13 / 7 / 2 / 0 · 🪙 50 / 30 / 10 / 0':'팀 승리 · 🪙 50 · 🏆 10 · 50XP')+'</p><div class="multiRoster">'+roster+'</div><div class="pickGrid">'+offer.map(id=>'<button class="pick '+(app.multiSelected===id?'active':'')+'" data-multi-hero="'+id+'" '+(me?.ready?'disabled':'')+'><img src="'+heroImg(id)+'"><strong>'+escapeHTML(HM[id].name)+'</strong><small>파워 '+heroLevel(id)+' · ♥ '+heroPreview(id).hp+'</small></button>').join('')+'</div><label class="socialRow">시작 각도 <input id="multiAngle" type="range" min="-70" max="70" value="'+(app.multiAngle||0)+'" '+(me?.ready?'disabled':'')+'><output id="multiAngleLabel">'+(app.multiAngle||0)+'°</output></label><p class="micro" id="multiCountdown"></p><div class="subLinks"><button id="multiReady" class="action" '+(me?.ready?'disabled':'')+'>'+(me?.ready?'다른 플레이어 준비 중…':'준비 완료')+'</button><button id="multiCancel" class="action alt">메인으로</button></div><p id="multiError" class="micro"></p>','multi_pick');
 overlayContent.querySelectorAll('[data-multi-hero]').forEach(b=>b.onclick=()=>{app.multiSelected=b.dataset.multiHero;multiplayerLobby();sound('select')});$('#multiAngle').oninput=e=>{app.multiAngle=+e.target.value;$('#multiAngleLabel').textContent=app.multiAngle+'°';};$('#multiReady').onclick=async()=>{const b=$('#multiReady');b.disabled=true;try{await sendAction('multi_ready',{hero:app.multiSelected,angle:app.multiAngle||0})}catch(e){multiplayerError(e);b.disabled=false}};$('#multiCancel').onclick=home;updateMultiplayerCountdown();}
function updateMultiplayerCountdown(){const el=$('#multiCountdown');if(el&&app.multiLobby)el.textContent='모두 준비하면 시작 · '+Math.max(0,Math.ceil((app.multiLobby.deadline-Date.now())/1000))+'초 뒤 미준비 캐릭터는 자동 선택';}
setInterval(updateMultiplayerCountdown,1000);
function multiplayerResult(m){multiplayerToken++;features?.cancelLoading();app.roundResult=true;app.matchEnd=true;app.royaleData=m.state;app.multiMode=m.mode;const prize=m.reward||{},teams=m.state.teams,me=m.state.actors.find(a=>a.sid===app.session),won=prize.won;
 const rows=teams?m.state.actors.map(a=>'<div class="socialRow"><img style="width:44px;height:44px;object-fit:contain" src="'+heroImg(a.id)+'"><span><b>'+escapeHTML(a.name)+'</b><small>'+(a.team===me?.team?'우리 팀':'상대 팀')+' · 피해 '+Math.round(m.state.damage[a.side]||0)+' · '+(a.kills||0)+' 처치</small></span></div>').join(''):m.placements.map(p=>'<div class="socialRow"><b>'+p.rank+'위</b><span>'+escapeHTML(p.name)+(p.sid===app.session?' · 나':'')+'</span></div>').join('');
 display('<div class="eyebrow">'+multiplayerLabels[m.mode]+' 종료</div><h2>'+(teams?(won?'🏆 팀 승리!':'팀 패배'):(prize.rank===1?'🏆 1등 달성!':prize.rank+'등'))+'</h2><p>🪙 +'+(prize.coins||0)+' · 🏆 +'+(prize.trophies||0)+' · XP +'+(prize.xp||0)+'</p>'+(m.forfeit?'<p class="micro">탈주가 발생한 경기는 XP를 지급하지 않습니다.</p>':'')+'<div class="socialRows">'+rows+'</div><div class="subLinks"><button id="multiReplay" class="action">다시 매칭</button><button id="multiHome" class="action alt">메인으로</button></div>','multi_result');$('#multiHome').onclick=home;$('#multiReplay').onclick=()=>startOnline(m.mode);sound(won?'win':'lose');refreshPlayer();}
const multiplayerBaseEvent=onEvent;
onEvent=function(m){if(!m.event.startsWith('multi_'))return multiplayerBaseEvent(m);switch(m.event){
 case 'multi_queue':app.multiMode=m.mode;waiting(m.label+' · '+m.count+'/'+m.needed+'명','랜덤 매칭');overlayContent.insertAdjacentHTML('beforeend','<button class="action alt" id="multiCancelQueue">매칭 취소</button>');$('#multiCancelQueue').onclick=home;break;
 case 'multi_matched':app.multiMode=m.mode;app.multiIntroUntil=Date.now()+5000;app.multiSelected=null;app.multiAngle=0;features?.runLoading(5000,'match');display('<div class="eyebrow">'+escapeHTML(m.label)+'</div><h2>매칭 완료!</h2><p>캐릭터를 선택해 주세요.</p>','matched');break;
 case 'multi_lobby':app.multiLobby=m;app.multiOffer=m.offer;app.multiMode=m.mode;{const token=++multiplayerToken;setTimeout(()=>{if(token===multiplayerToken&&app.multiLobby)multiplayerLobby()},m.resume?0:Math.max(0,(app.multiIntroUntil||0)-Date.now()));}break;
 case 'multi_start':multiplayerToken++;app.multiLobby=null;app.multiMode=m.mode;app.roundResult=false;app.matchEnd=false;startRoyaleBattle(m.state,0);app.mode=m.mode;$('#roundTag').textContent=multiplayerLabels[m.mode];sound('start');break;
 case 'multi_state':app.royaleData=m.state;handleFx(m.state);if(app.screen==='royaleBattle')$('#roundTag').textContent=multiplayerLabels[m.state.mode]+' · '+(m.state.teams?'팀 생존 '+m.state.actors.filter(a=>a.hp>0).length:'생존 '+m.state.actors.filter(a=>a.hp>0).length);break;
 case 'multi_end':multiplayerResult(m);break;
 case 'multi_cancelled':features?.cancelLoading();app.multiLobby=null;multiplayerToken++;display('<h2>매칭 취소</h2><p>'+escapeHTML(m.message)+'</p><div class="subLinks"><button class="action" id="multiRetry">다시 매칭</button><button id="multiBack">메인으로</button></div>','multi_cancelled');$('#multiRetry').onclick=()=>startOnline(app.multiMode);$('#multiBack').onclick=home;break;
 case 'multi_left':home();break;
 }};
const multiplayerBaseDraw=drawRoyale;
drawRoyale=function(){multiplayerBaseDraw();const s=app.royaleData;if(!s?.mode)return;const me=s.actors.find(a=>a.sid===app.session);ctx.save();if(s.teams){ctx.fillStyle='#f7faf5';ctx.fillRect(0,0,650,86);ctx.textAlign='left';ctx.font='bold 22px sans-serif';ctx.fillStyle='#1478bb';ctx.fillText('🛡️ 우리 팀 '+s.actors.filter(a=>a.team===me?.team&&a.hp>0).length+'명',24,33);ctx.fillStyle='#d4465a';ctx.fillText('⚔️ 상대 팀 '+s.actors.filter(a=>a.team!==me?.team&&a.hp>0).length+'명',310,33);ctx.fillStyle='#233750';ctx.fillText(me?.hp>0?'내 HP '+Math.ceil(me.hp)+' / '+me.max:'탈락 · 팀원 관전 중',24,65);}for(const a of s.actors){if(a.hp<=0)continue;ctx.strokeStyle=a.sid===app.session?'#ffcb3d':s.teams?(a.team===me?.team?'#37aaff':'#ff546b'):'#ff546b';ctx.lineWidth=a.sid===app.session?6:3;ctx.beginPath();ctx.arc(a.x,a.y,a.r+8,0,Math.PI*2);ctx.stroke();ctx.font='bold 15px sans-serif';ctx.textAlign='center';ctx.fillStyle='#172d46';ctx.fillText(a.sid===app.session?'나':a.name,a.x,a.y-a.r-18);}ctx.restore();};
const multiplayerStyle=document.createElement('style');multiplayerStyle.textContent='.modeOptions{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px!important}.modeOptions .modeChip{min-width:0!important}.modeOptions .modeChip span{font-size:20px}.multiRoster{display:grid;grid-template-columns:1fr;gap:3px;max-height:230px;overflow-y:auto;margin:10px 0}.multiRoster h3{margin:8px 0 2px}.multiRoster .socialRow{min-height:46px}.overlayContent:has(#multiReady) .pickGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));width:min(100%,460px);margin:12px auto;gap:8px}.overlayContent:has(#multiReady) .pick img{height:78px;width:80px;object-fit:contain}.overlayContent:has(#multiReady) .pick strong{font-size:12px}.overlayContent:has(#multiReady){max-height:100%;overflow-y:auto}@media(max-width:650px){.multiRoster{max-height:180px}.overlayContent:has(#multiReady) .pick img{height:58px;width:60px}.modeChip{padding:8px 10px}}';document.head.append(multiplayerStyle);

