'use strict';
const crypto=require('node:crypto');
const MODES={duo:{size:4,label:'2대2',teamSize:2},trio:{size:6,label:'3대3',teamSize:3},royale4:{size:4,label:'4인 배틀로얄',teamSize:0}};
const ROYALE_REWARDS={1:{coins:50,trophies:13},2:{coins:30,trophies:7},3:{coins:10,trophies:2},4:{coins:0,trophies:0}};
module.exports=function createMultiplayer(api){
 const {sessions,profile,send,migrate,persist,progression,season,contribution,publicUser,offer,exitOther,engine}=api;
 const arena=engine.forArena(1400,950),queues=new Map(Object.keys(MODES).map(k=>[k,[]])),matches=new Map();let serial=0;
 const user=id=>profile(sessions.get(id));
 const emit=(r,event,data)=>r.players.forEach(id=>send(sessions.get(id),event,data));
 function queued(s){for(const q of queues.values())if(q.includes(s.id))return true;return false;}
 function counts(){return {queues:Object.fromEntries([...queues].map(([k,v])=>[k,v.length])),matches:matches.size};}
 function notify(mode){const q=queues.get(mode);for(const id of q)send(sessions.get(id),'multi_queue',{mode,label:MODES[mode].label,count:q.length,needed:MODES[mode].size});}
 function removeQueue(s){for(const [mode,q] of queues){const i=q.indexOf(s.id);if(i>=0){q.splice(i,1);notify(mode)}}s.multiQueue=null;}
 function lobby(r,s){const players=r.players.map((sid,i)=>({sid,team:r.teams?.[i]??null,...publicUser(user(sid)),hero:r.picks[i]||null,ready:r.ready.has(i)}));const payload={mode:r.mode,label:MODES[r.mode].label,players,deadline:r.deadline};if(s)send(s,'multi_lobby',{...payload,offer:r.offers[r.players.indexOf(s.id)]||[],resume:true});else for(const id of r.players)send(sessions.get(id),'multi_lobby',{...payload,offer:r.offers[r.players.indexOf(id)]||[]});}
 function buildTeams(ids,size){const teams=ids.map(()=>null),sums=[0,0],n=[0,0];const ordered=ids.map((id,i)=>({i,t:progression.total(user(id)),j:crypto.randomInt(1e6)})).sort((a,b)=>b.t-a.t||a.j-b.j);for(const p of ordered){const t=n[0]>=size?1:n[1]>=size?0:sums[0]===sums[1]?(n[0]===n[1]?crypto.randomInt(2):n[0]<n[1]?0:1):sums[0]<sums[1]?0:1;teams[p.i]=t;sums[t]+=p.t;n[t]++;}return teams;}
 function create(mode,ids){const cfg=MODES[mode],r={id:'multi'+(++serial),mode,players:ids,profiles:ids.map(id=>user(id).id),teams:cfg.teamSize?buildTeams(ids,cfg.teamSize):null,picks:ids.map(()=>null),angles:ids.map(()=>0),offers:ids.map(id=>offer(user(id))),ready:new Set(),phase:'pick',created:Date.now(),deadline:Date.now()+40000,left:new Set(),sim:null,timer:null,pickTimer:null,statsDone:false,rewards:{}};matches.set(r.id,r);for(const id of ids){const s=sessions.get(id);s.multi=r.id;s.multiQueue=null;send(s,'multi_matched',{mode,label:cfg.label})}lobby(r);r.pickTimer=setTimeout(()=>{if(r.phase!=='pick')return;for(let i=0;i<r.players.length;i++){r.picks[i]||=r.offers[i][0];r.ready.add(i)}start(r)},40000);return r;}
 function enqueue(s,mode){if(!MODES[mode])throw Error('올바른 대전 모드를 선택하세요.');const u=profile(s);if(!u)throw Error('프로필을 먼저 연결하세요.');const active=matches.get(s.multi);if(active&&['pick','battle'].includes(active.phase))throw Error('진행 중인 대전을 먼저 종료하세요.');for(const other of sessions.values())if(other.id!==s.id&&other.profile===s.profile&&(queued(other)||['pick','battle'].includes(matches.get(other.multi)?.phase)))throw Error('이 계정은 이미 매칭 중이거나 대전 중이에요.');exitOther(s);removeQueue(s);const q=queues.get(mode);for(let i=q.length-1;i>=0;i--){const cand=sessions.get(q[i]);if(!cand?.stream||cand.stream.destroyed||!user(q[i])){if(cand)cand.multiQueue=null;q.splice(i,1)}}q.push(s.id);s.multiQueue=mode;notify(mode);if(q.length>=MODES[mode].size){const ids=q.splice(0,MODES[mode].size);create(mode,ids);notify(mode)}}
 function start(r){if(r.phase!=='pick')return;clearTimeout(r.pickTimer);r.pickTimer=null;for(let i=0;i<r.players.length;i++)r.picks[i]||=r.offers[i][0];r.sim=arena.create(r.picks,r.angles,crypto.randomBytes(4).readUInt32BE(),r.players.map((id,i)=>user(id)?.levels?.[r.picks[i]]||0));r.sim.mode=r.mode;r.sim.teams=r.teams;r.sim.manualUlt=r.players.map(()=>true);const rows=[0,0];r.sim.actors.forEach((a,i)=>{a.sid=r.players[i];a.name=user(a.sid)?.nick||'플레이어';a.team=r.teams?.[i]??null;if(!r.teams){const angle=r.angles[i]*Math.PI/180,vx=a.vx,vy=a.vy;a.vx=vx*Math.cos(angle)-vy*Math.sin(angle);a.vy=vx*Math.sin(angle)+vy*Math.cos(angle);}if(r.teams){a.x=a.team===0?290:1110;a.y=220+rows[a.team]++*220;a.vx=(a.team===0?1:-1)*Math.cos(r.angles[i]*Math.PI/180)*engine.HERO_BY_ID[a.id].speed;a.vy=Math.sin(r.angles[i]*Math.PI/180)*engine.HERO_BY_ID[a.id].speed;}});r.phase='battle';emit(r,'multi_start',{state:r.sim,mode:r.mode});r.timer=setInterval(()=>step(r),65);}
 function step(r){if(r.phase!=='battle')return;let dt=.065;while(dt>0&&!r.sim.finished){const h=Math.min(.05,dt);arena.tick(r.sim,h);dt-=h}emit(r,'multi_state',{state:r.sim});if(r.sim.finished)finish(r);}
 function placements(r){if(r.teams)return [];const winner=r.sim.winner,losers=[...new Set(r.sim.eliminations)].filter(i=>i!==winner).reverse();for(const a of r.sim.actors)if(a.side!==winner&&!losers.includes(a.side))losers.push(a.side);return [winner,...losers].map((i,n)=>({sid:r.players[i],name:r.sim.actors[i].name,rank:n+1}));}
 function reward(r){if(r.statsDone)return;r.statsDone=true;const winnerTeam=r.teams?.[r.sim.winner],places=placements(r);for(let i=0;i<r.players.length;i++){const id=r.players[i],u=api.profiles.get(r.profiles[i]);if(!u||r.left.has(id))continue;migrate(u);const won=r.teams?r.teams[i]===winnerTeam:i===r.sim.winner;const prize=r.teams?{coins:won?50:0,trophies:won?10:0}:ROYALE_REWARDS[places.find(p=>p.sid===id)?.rank||4];u.coins=(u.coins||0)+prize.coins;u.trophies[r.picks[i]]=(u.trophies[r.picks[i]]||0)+prize.trophies;if(won){u.wins=(u.wins||0)+1;contribution(u)}else u.losses=(u.losses||0)+1;if(!r.forfeit)season.record(u,[{hero:r.picks[i],won}],won);r.rewards[id]={...prize,xp:won&&!r.forfeit?50:0,won,rank:places.find(p=>p.sid===id)?.rank||null};}persist();}
 function result(r,s){if(!s)return;send(s,'multi_end',{mode:r.mode,state:r.sim,winner:r.sim.winner,winnerTeam:r.teams?.[r.sim.winner]??null,placements:placements(r),reward:r.rewards[s.id]||{coins:0,trophies:0,xp:0},forfeit:!!r.forfeit});}
 function finish(r){if(r.phase==='complete')return;clearInterval(r.timer);clearTimeout(r.pickTimer);r.timer=r.pickTimer=null;r.phase='complete';reward(r);for(const id of r.players)result(r,sessions.get(id));r.cleanup=setTimeout(()=>dispose(r),120000);}
 function dispose(r){clearInterval(r.timer);clearTimeout(r.pickTimer);clearTimeout(r.cleanup);matches.delete(r.id);for(const id of r.players){const s=sessions.get(id);if(s?.multi===r.id)s.multi=null;}}
 function leave(s){removeQueue(s);const r=matches.get(s.multi);s.multi=null;if(!r)return;if(r.phase==='complete'){r.left.add(s.id);if(r.players.every(id=>sessions.get(id)?.multi!==r.id))dispose(r);return;}r.left.add(s.id);if(r.phase==='pick'){emit(r,'multi_cancelled',{message:'참가자가 나가서 매칭이 취소됐어요. 다시 매칭해 주세요.'});dispose(r);return;}const i=r.players.indexOf(s.id),a=r.sim?.actors[i];if(a?.hp>0){a.hp=0;r.sim.eliminations.push(i);r.forfeit=true;}if(r.players.every(id=>r.left.has(id)))dispose(r);else step(r);}
 function resume(s){if(s.multiQueue){notify(s.multiQueue);return;}const r=matches.get(s.multi);if(!r)return;if(r.phase==='pick')lobby(r,s);else if(r.phase==='battle'){send(s,'multi_start',{state:r.sim,mode:r.mode});send(s,'multi_state',{state:r.sim})}else result(r,s);}
 function action(s,m){if(m.action==='multi_queue'){enqueue(s,String(m.mode));return true;}if(m.action==='multi_leave'){leave(s);send(s,'multi_left');return true;}const r=matches.get(s.multi);if(!r)return false;const i=r.players.indexOf(s.id);if(m.action==='multi_ready'){if(r.phase!=='pick'||!r.offers[i].includes(m.hero)||!user(s.id)?.owned.includes(m.hero))throw Error('보유한 캐릭터 중에서 선택하세요.');if(!Number.isFinite(m.angle)||Math.abs(m.angle)>70)throw Error('각도는 -70~70도만 가능해요.');r.picks[i]=m.hero;r.angles[i]=m.angle;r.ready.add(i);lobby(r);if(r.ready.size===r.players.length)start(r);return true;}if(m.action==='royale_super'||m.action==='multi_super'){if(r.phase!=='battle'||!arena.useUltimate(r.sim,i))throw Error('궁극기를 아직 사용할 수 없어요.');emit(r,'multi_state',{state:r.sim});return true;}if(m.action==='emote'){if(r.phase!=='battle')throw Error('전투 중에만 핀을 사용할 수 있어요.');const pin=api.cosmetics.emote(user(s.id),s,m);emit(r,'emote',{...pin,side:i,sid:s.id});return true;}return false;}
 return {action,leave,resume,counts,matches,queues,step,reward,MODES};
};
module.exports.MODES=MODES;module.exports.ROYALE_REWARDS=ROYALE_REWARDS;
