/* Season 1 screens and non-obstructing combat controls. */
window.createSeasonUI=function(api){
 const {app,E,H,HM,heroImg,esc,modal,content,title,call,auth,profile,refresh,toast,music}=api;
 const mobile=()=>navigator.maxTouchPoints>0&&Math.min(screen.width,screen.height)<900;
 function orient(){const rotated=mobile()&&innerHeight>innerWidth;document.body.classList.toggle('virtualLandscape',rotated);document.body.classList.toggle('mobileLandscape',mobile());document.body.style.setProperty('--arena-view-width',(rotated?innerHeight:innerWidth)+'px');document.body.style.setProperty('--arena-view-height',(rotated?innerWidth:innerHeight)+'px');}
 orient();window.addEventListener('resize',orient);window.addEventListener('orientationchange',orient);
 document.addEventListener('pointerdown',async()=>{if(!mobile())return;try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();await screen.orientation?.lock?.('landscape');}catch{}orient();},{once:true});
 let loadToken=0,pending=false,lastReady=new Set(),lastImpact=0,questBusy=false;
 const dock=document.createElement('div');dock.className='ultDock';dock.hidden=true;document.querySelector('.panelFooter').before(dock);
 const loading=document.createElement('div');loading.className='seasonLoading';loading.hidden=true;loading.innerHTML=`<div class="loadingScene"><img class="loadingArt" src="/loading-season1.png" alt="Lil_Ago Arena Season 1"><div class="loadingActor actorCactus"></div><div class="loadingActor actorKoala"></div><div class="loadingActor actorMoai"></div><div class="loadingSparkles">✦　　✧　　　✦　　　　　✧</div><div class="loadingSteam"></div></div><div class="loadPanel"><strong>Lil_Ago Arena</strong><span id="loadCaption">Season 1 · 아레나 준비 중</span><div class="loadTrack"><i></i></div><small id="loadPercent">0%</small></div>`;document.body.append(loading);
 const readyNote=document.createElement('div');readyNote.className='ultimateReadyToast';readyNote.hidden=true;readyNote.textContent='⚡ 궁극기 준비 완료!';document.body.append(readyNote);
 let impact=getSavedImpact();function getSavedImpact(){try{return localStorage.getItem('arena_impact')!=='off'}catch{return true}}
 function setImpact(value){impact=value;try{localStorage.setItem('arena_impact',value?'on':'off')}catch{} }
 async function runLoading(ms=5000,kind='battle'){
  if(['battle','royaleBattle'].includes(app.screen)||kind==='battle')return false;
  const token=++loadToken;app.loading=true;app.loadingKind=kind;music.setLobby(false);loading.hidden=false;loading.classList.remove('arriving');void loading.offsetWidth;loading.classList.add('arriving');loading.querySelector('.loadTrack i').style.animationDuration=ms+'ms';
  const start=performance.now();await new Promise(resolve=>{function step(){if(token!==loadToken){resolve();return}const n=Math.min(100,Math.floor((performance.now()-start)/ms*100));loading.querySelector('#loadPercent').textContent=n+'%';if(n>=100){resolve();return}setTimeout(step,40)}step()});
  if(token!==loadToken)return false;loading.hidden=true;app.loading=false;app.loadingKind=null;music.setLobby(app.screen==='home');return true;
 }
 function cancelLoading(){loadToken++;app.loading=false;loading.hidden=true;}
 function actorState(){const s=app.screen==='royaleBattle'?app.royaleData:app.combat;return {s,side:app.screen==='royaleBattle'?s?.actors.findIndex(a=>a.sid===app.session):(app.online?app.side:0)};}
 function active(){return ['battle','royaleBattle'].includes(app.screen)&&!app.roundResult&&!app.loading&&app.mode!=='cpu';}
 async function trigger(side){if(!active()||pending)return;const {s}=actorState();const f=s?.actors[side];if(!f||f.hp<=0||f.ultTimer>0)return;pending=true;try{if(app.online)await api.send(app.screen==='royaleBattle'?'royale_super':'ultimate');else if(!E.useUltimate(s,side))toast('지금은 궁극기를 사용할 수 없어요.');}catch(e){toast(e.message)}finally{pending=false}}
 function updateUltimate(){
  const {s,side}=actorState(),show=active()&&s&&!s.finished;dock.hidden=!show;if(!show)return;
  const sides=app.mode==='local'?[0,1]:[side];
  if(dock.dataset.key!==sides.join(',')+app.mode){dock.dataset.key=sides.join(',')+app.mode;dock.innerHTML=sides.map(i=>`<button class="ultimateControl" data-ult="${i}" aria-label="궁극기 사용"><span class="ultIcon">⚡</span><span class="ultCopy"><b>${app.mode==='local'?(i+1)+'P ':''}궁극기</b><small class="ultLabel">충전 중</small><span class="ultMeter"><i></i></span></span><kbd>${i===1&&app.mode==='local'?'Enter':'SPACE'}</kbd></button>`).join('');dock.querySelectorAll('[data-ult]').forEach(b=>b.onclick=()=>trigger(+b.dataset.ult));}
  for(const i of sides){const f=s.actors[i],b=dock.querySelector(`[data-ult="${i}"]`);if(!f||!b)continue;const pct=Math.max(0,Math.min(100,(1-f.ultTimer/(f.ultCooldown||6.2))*100));const charged=f.ultTimer<=0&&f.hp>0;const blocked=f.stun>0||f.freeze>0||f.mute>0||f.airborne>0||f.ultActive||(f.forceHold&&s.t<f.forceHold.until);b.disabled=!charged||!!blocked||pending;b.classList.toggle('charged',charged);b.querySelector('.ultMeter i').style.width=pct+'%';b.querySelector('.ultLabel').textContent=f.hp<=0?'탈락':charged?(blocked?'행동 불가':'준비 완료 · 사용하기'):Math.floor(pct)+'%';
   const key=app.round+':'+i+':'+f.id+':'+(f.ultUses||0);if(charged&&!lastReady.has(key)){lastReady.add(key);readyNote.hidden=false;readyNote.classList.remove('play');void readyNote.offsetWidth;readyNote.classList.add('play');api.sound('ready');setTimeout(()=>readyNote.hidden=true,1700);}
  }
 }
 document.addEventListener('keydown',e=>{if(e.repeat||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable||!modal.classList.contains('hidden')||!active())return;const {side}=actorState();if(e.code==='Space'||(e.code==='Enter'&&app.mode==='local')){e.preventDefault();trigger(e.code==='Enter'?1:side);}});
 function hit(type){if(!impact)return;const now=performance.now();if(now-lastImpact<90)return;lastImpact=now;const arena=document.querySelector('#arena');arena.classList.remove('impact','bigImpact');void arena.offsetWidth;arena.classList.add(type==='death'||type==='super'?'bigImpact':'impact');}
 function open(kind,name){api.setActive(kind);modal.classList.remove('hidden');title.textContent=name;content.innerHTML='<p>불러오는 중…</p>';}
 async function getProfile(){await api.init();const r=await call('get',auth());api.setProfile(r.profile);refresh();return r.profile;}
 async function claim(action,data,render){if(questBusy)return;questBusy=true;try{const v=await call(action,{...auth(),...data});api.setProfile(v.profile);refresh();toast(v.reward?.hero?'🎉 '+HM[v.reward.hero].name+' 획득!':'🪙 '+(v.reward?.coins||0)+'코인 수령!');await render();}catch(e){toast(e.message)}finally{questBusy=false;}}
 async function quests(){open('quests','🎯 일일 퀘스트 · 출석');try{const p=await getProfile(),a=p.attendance;content.innerHTML=`<div class="seasonSummary"><b>매일 작은 보상, 꾸준한 성장</b><small>한국 시간 자정 초기화 · 봇/부전승은 일일 퀘스트에 포함되지 않아요.</small></div><h3>📅 7일 출석 보상</h3><div class="attendanceGrid">${[25,'캐릭터',50,50,'캐릭터',75,100].map((r,i)=>{const cycle=a.count%7||((a.todayClaimed&&a.count)?7:0);return `<article class="attendanceTile ${i+1===a.nextDay&&!a.todayClaimed?'next':''} ${i<cycle?'collected':''}"><small>${i+1}일차</small><span>${typeof r==='number'?'🪙':'🎁'}</span><b>${typeof r==='number'?r+'코인':'미보유 캐릭터'}</b>${i<cycle?'<small>✓ 수령</small>':''}</article>`}).join('')}</div><button class="primary" id="attendanceClaim" ${a.todayClaimed?'disabled':''}>${a.todayClaimed?'✓ 오늘 출석 완료':'오늘 '+a.nextDay+'일차 보상 받기'}</button><p class="micro">2·5일차: 랜덤 미보유 캐릭터. 모두 보유했다면 500코인. 7일 후 새 주기로 이어져요.</p><h3>🎯 오늘의 퀘스트</h3><div class="questCards">${p.daily.quests.map(q=>`<article class="questCard"><div><b>${q.title}</b><small>${Math.min(q.need,q.progress)} / ${q.need} · 🪙 ${q.coins}</small><div class="questMeter"><i style="width:${Math.min(100,q.progress/q.need*100)}%"></i></div></div><button data-quest="${q.id}" ${q.claimed||q.progress<q.need?'disabled':''}>${q.claimed?'✓ 완료':'받기'}</button></article>`).join('')}</div>`;content.querySelector('#attendanceClaim').onclick=()=>claim('attendance_claim',{},quests);content.querySelectorAll('[data-quest]').forEach(b=>b.onclick=()=>claim('quest_claim',{quest:b.dataset.quest},quests));}catch(e){content.textContent=e.message}}
 function passReward(t,track){if(track==='premium')return '🪙 50';return t===10?'🪙 25 + 900':t===20?'🪙 25 + 🎁 미보유 캐릭터':t===30?'🪙 25 + ⭐ 캐릭터 선택':'🪙 25';}
 async function pass(){open('pass','🎟️ Season 1 · 시즌 패스');try{const p=await getProfile(),s=p.seasonPass;content.innerHTML=`<div class="passHero"><span>SEASON 1</span><h3>Lil_Ago Arena</h3><p>정상 온라인 승리 +50XP · 100XP당 1티어 · 30티어 / 3000XP</p><div class="passProgress"><i style="width:${s.xp/3000*100}%"></i></div><b>${s.xp} / 3000XP · 티어 ${s.tier} / 30</b></div><div class="passInfo"><b>${s.premium?'👑 프리미엄 이용 중':'🔒 프리미엄 패스'}</b><small>구매는 디스코드 문의 바랍니다</small><span>관리자가 지급하면 이용 가능 · 지난 티어 보상도 수령 가능</span></div><div class="passScroll" tabindex="0"><div class="passLaneLabels"><span>👑 프리미엄</span><span>티어</span><span>🎟️ 무료 패스</span></div><div class="passTrack">${Array.from({length:30},(_,i)=>{const t=i+1;return `<section class="passTier ${t%10===0?'milestone':''}" data-tier="${t}">${['premium','free'].map(track=>{const done=s.claimed.includes(track+':'+t),locked=t>s.tier||(track==='premium'&&!s.premium);return `${track==='free'?'<div class="tierNumber">'+t+'</div>':''}<button class="passReward ${track} ${done?'claimed':''}" data-pass-tier="${t}" data-track="${track}" ${done||locked?'disabled':''}><span>${track==='premium'?'👑':t===20?'🎁':t===30?'⭐':'🪙'}</span><b>${passReward(t,track)}</b><small>${done?'✓ 받음':locked?'🔒 잠김':'보상 받기'}</small></button>`}).join('')}</section>`}).join('')}</div></div><p class="micro">기본 보상: 무료 25코인 / 프리미엄 50코인. 무료 특별 보상: 10티어 +900코인, 20티어 랜덤 미보유 캐릭터(전부 보유 시 +500코인), 30티어 원하는 미보유 캐릭터(전부 보유 시 +1000코인).</p>`;content.querySelectorAll('[data-pass-tier]').forEach(b=>b.onclick=()=>{const t=+b.dataset.passTier,track=b.dataset.track;const missing=H.filter(h=>!p.owned.includes(h.id));if(t===30&&track==='free'&&missing.length){content.innerHTML=`<h3>⭐ 원하는 캐릭터를 선택하세요</h3><p>선택한 캐릭터와 기본 25코인을 받아요.</p><div class="fighterGrid">${missing.map(h=>`<button class="fighterCard" data-choice="${h.id}"><img src="${heroImg(h.id)}"><strong>${esc(h.name)}</strong></button>`).join('')}</div><button id="returnPass">패스로 돌아가기</button>`;content.querySelectorAll('[data-choice]').forEach(c=>c.onclick=()=>claim('pass_claim',{tier:t,track,hero:c.dataset.choice},pass));content.querySelector('#returnPass').onclick=pass;}else claim('pass_claim',{tier:t,track},pass)});const current=content.querySelector(`[data-tier="${Math.min(30,Math.max(1,s.tier+1))}"]`);if(current)content.querySelector('.passScroll').scrollLeft=Math.max(0,current.offsetLeft-160);}catch(e){content.textContent=e.message}}
 async function shop(){open('gacha','🛍️ 상점 · 캐릭터 뽑기');try{await api.init();const p=profile();content.innerHTML=`<div class="shopWallet"><b id="shopCoins">🪙 ${p.coins.toLocaleString()}</b><span>보유 ${p.owned.length} / ${H.length}</span></div><div class="drawOffers"><article><span class="giftArt">🎁</span><h3>캐릭터 1회</h3><p>모든 캐릭터 동일 확률</p><button class="primary" data-draw="1">🪙 100 · 1회 뽑기</button></article><article class="bestOffer"><small>100코인 할인</small><span class="giftArt">🎁🎁</span><h3>캐릭터 10회</h3><p>한 번에 10개 열기</p><button class="primary" data-draw="10">🪙 900 · 10회 뽑기</button></article></div><p class="micro">캐릭터당 ${(100/H.length).toFixed(2)}% · 중복 뽑기에는 보상이 없어요. 관리자 캐릭터 선물 중복만 500코인으로 대체됩니다.</p><div id="newDrawResults" aria-live="polite"></div><details><summary>전체 캐릭터 · 보유 상태 보기</summary><div class="shopRoster">${H.map(h=>`<div><img loading="lazy" src="${heroImg(h.id)}"><b>${esc(h.name)}</b><small>${p.owned.includes(h.id)?'✓ 보유':'미보유'}</small></div>`).join('')}</div></details>`;
 let busy=false;content.querySelectorAll('[data-draw]').forEach(b=>b.onclick=async()=>{if(busy)return;busy=true;const buttons=[...content.querySelectorAll('[data-draw]')];buttons.forEach(x=>x.disabled=true);try{const v=await call('draw',{...auth(),count:+b.dataset.draw});api.setProfile(v.profile);refresh();if(api.getActive()!=='gacha')return;content.querySelector('#shopCoins').textContent='🪙 '+v.profile.coins.toLocaleString();let seen=new Set();content.querySelector('#newDrawResults').innerHTML=`<h3>🎊 뽑기 결과</h3><div class="drawCards">${v.drawn.map((id,i)=>{const fresh=v.newIds.includes(id)&&!seen.has(id);seen.add(id);return `<article class="revealCard ${fresh?'newFighter':''}" style="animation-delay:${i*.08}s"><img src="${heroImg(id)}"><b>${esc(HM[id].name)}</b><small>${fresh?'✨ NEW!':'중복'}</small></article>`}).join('')}</div>`;api.sound('pick');}catch(e){toast(e.message)}finally{busy=false;buttons.forEach(x=>x.disabled=false)}});}catch(e){content.textContent=e.message}}
 async function leaderboard(){open('board','🏆 랭킹');try{await api.init();const r=await fetch(api.base()+'/leaderboard');if(!r.ok)throw Error('랭킹을 불러오지 못했어요.');const v=await r.json();let sort='trophies';content.innerHTML=`<div class="leaderSummary"><b>내 총 트로피 🏆 ${(profile().totalTrophies||0).toLocaleString()}</b><span>${profile().wins||0}승</span></div><div class="leaderTools"><input id="leaderSearch" placeholder="닉네임 또는 친구 코드 검색"><select id="leaderSort"><option value="trophies">트로피순</option><option value="wins">승리순</option></select><button id="leaderRefresh">↻ 새로고침</button></div><p class="micro">전체 유저 순위 · 상위 100명 표시</p><div id="leaderRows"></div>`;
 function render(){const q=content.querySelector('#leaderSearch').value.trim().toLowerCase(),data=[...(v.players||[])].sort((a,b)=>sort==='wins'?b.wins-a.wins||(b.totalTrophies||0)-(a.totalTrophies||0):(b.totalTrophies||0)-(a.totalTrophies||0)||b.wins-a.wins);content.querySelector('#leaderRows').innerHTML=data.map((u,i)=>({...u,place:i+1})).filter(u=>(u.nick+' '+u.tag).toLowerCase().includes(q)).map(u=>`<article class="leaderRow ${u.tag===profile().tag?'isMe':''}"><b class="place ${u.place<=3?'podium':''}">${u.place<=3?['🥇','🥈','🥉'][u.place-1]:u.place}</b><img src="${heroImg(HM[u.avatar]?u.avatar:'pizza')}"><div><b>${esc(u.nick)} ${u.tag===profile().tag?'(나)':''}</b><small>#${esc(u.tag)}</small></div><strong>🏆 ${u.totalTrophies||0}<small>${u.wins||0}승</small></strong></article>`).join('')||'<p>검색 결과가 없어요.</p>';}
 content.querySelector('#leaderSearch').oninput=render;content.querySelector('#leaderSort').onchange=e=>{sort=e.target.value;render()};content.querySelector('#leaderRefresh').onclick=leaderboard;render();}catch(e){content.textContent=e.message}}
 return {runLoading,cancelLoading,updateUltimate,hit,quests,pass,shop,leaderboard,setImpact,getImpact:()=>impact,reset(){lastReady.clear();dock.dataset.key='';},resultStats(stats,rewards){return `<div class="resultStats">${stats.map((a,i)=>`<article class="resultFighter ${i===app.localWinner?'mvp':''}"><img src="${heroImg(a.hero)}"><h3>${esc(HM[a.hero]?.name||a.hero)}</h3>${i===app.localWinner?'<span class="mvpBadge">🏅 MVP · 승리</span>':''}<dl><div><dt>준 피해</dt><dd>${Math.round(a.damage||0)}</dd></div><div><dt>받은 피해</dt><dd>${Math.round(a.received||0)}</dd></div><div><dt>처치</dt><dd>${a.kills||0}</dd></div><div><dt>궁극기 사용</dt><dd>${a.ultUses||0}</dd></div></dl><small>${(rewards||[]).filter(r=>r.hero===a.hero).map(r=>'🏆 +'+r.amount).join(' ')}</small></article>`).join('')}</div>`}};
};
