'use strict';
const assert=require('node:assert/strict'),E=require('../engine'),season=require('../season').create(E.HEROES),M=require('../mastery')(E.HEROES),P=require('../progression').create(E.HEROES),C=require('../cosmetics');
const u={id:'u',tag:'TEST',owned:['pizza'],coins:0};season.migrate(u);P.migrate(u);C.migrate(u);M.migrate(u);
assert.equal(Object.keys(M.titles).length,36);assert.equal(M.titles.icecookie,'너는 빙신이구나');assert.equal(M.titles.fries,'더 뿌려줘?');assert.equal(M.titles.meatman,'채끝살... 채끝살');
u.trophies.pizza=999;M.migrate(u);assert(!u.mail.some(m=>m.titleHero));u.trophies.pizza=1000;M.migrate(u);M.migrate(u);assert.equal(u.mail.filter(m=>m.titleHero==='pizza').length,1);assert.throws(()=>M.action(u,{action:'mastery_equip',titleHero:'pizza'}),/수령/);const t=u.mail.find(m=>m.titleHero);P.action(u,{action:'mail_claim',mailId:t.id});M.action(u,{action:'mastery_equip',titleHero:'pizza'});assert.equal(M.publicFields(u).title,'피자는 어디?');P.action(u,{action:'mail_claim',mailId:t.id});assert.equal(u.titles.length,1);
season.record(u,[{hero:'pizza',won:true}],true);let reward=M.record(u,[{hero:'pizza',won:true,damage:100,kills:1},{hero:'pizza',won:false,damage:50}],true);assert.equal(reward.firstWinXP,50);assert.equal(u.season.xp,100);assert.equal(u.heroStats.pizza.plays,1);assert.equal(u.heroStats.pizza.rounds,2);assert.equal(u.heroStats.pizza.damage,150);assert.equal(u.heroStats.pizza.points,undefined);assert.equal(M.record(u,[{hero:'pizza'}],true).firstWinXP,0);const before=JSON.stringify(u.heroStats);M.record(u,[{hero:'pizza'}],true,true);assert.equal(JSON.stringify(u.heroStats),before);
u.trophies.rico=299;M.migrate(u);assert(!u.mail.some(m=>m.pin==='mastery_rico'));u.trophies.rico=300;M.migrate(u);M.migrate(u);assert.equal(u.mail.filter(m=>m.pin==='mastery_rico').length,1);assert(!u.mail.some(m=>m.border));const pin=u.mail.find(m=>m.pin==='mastery_rico');P.action(u,{action:'mail_claim',mailId:pin.id});C.migrate(u);assert(u.pins.includes('mastery_rico'));u.equippedBorder='pizza';u.masteryBorders=['pizza'];u.mail.push({id:'mastery-border:pizza',border:'pizza'});u.mail.push({id:'mastery-pin:moai',pin:'mastery_moai',claimed:false});M.migrate(u);assert.equal(u.equippedBorder,null);assert.deepEqual(u.masteryBorders,[]);assert(!u.mail.some(m=>m.border||m.pin==='mastery_moai'));u.season.xp=3000;u.firstWinDay=null;assert.equal(M.record(u,[{hero:'pizza'}],true).firstWinXP,0);
const oldSI=global.setInterval,oldST=global.setTimeout,oldCI=global.clearInterval,oldCT=global.clearTimeout;let jobs=[];global.setInterval=fn=>{const j={fn};jobs.push(j);return j;};global.setTimeout=fn=>({fn});global.clearInterval=j=>{if(j)j.closed=true;};global.clearTimeout=()=>{};
try{
 const sessions=new Map(),profiles=new Map(),events=[],clans=new Map(),rooms=new Map(),royales=new Map();let saves=0,multi,live;
 const api={sessions,profiles,clans,rooms,royales,engine:E,profile:s=>s&&profiles.get(s.profile),send:(s,event,data)=>{if(s)events.push({sid:s.id,event,...data});},migrate:v=>{season.migrate(v);P.migrate(v);C.migrate(v);M.migrate(v);return v;},persist:()=>saves++,save:()=>saves++,progression:P,season,mastery:M,contribution:()=>{},publicUser:v=>({id:v.id,nick:v.nick}),offer:v=>v.owned.slice(0,3),exitOther:s=>multi.leave(s),cosmetics:C,busy:s=>!!(s.multiQueue||multi?.matches.get(s.multi)&&multi.matches.get(s.multi).phase!=='complete')};
 function player(i){const v=api.migrate({id:'p'+i,tag:'TAG'+i,nick:'P'+i,owned:['pizza','rico','grannyduo','fries'],coins:0,friends:[]});profiles.set(v.id,v);const s={id:'session'+i,profile:v.id,stream:{destroyed:false}};sessions.set(s.id,s);return s;}
 const ps=Array.from({length:12},(_,i)=>player(i)),get=s=>api.profile(s);get(ps[0]).friends=[get(ps[1]).id,get(ps[2]).id];get(ps[1]).friends=[get(ps[0]).id];
 const parties=require('../parties')(api);api.parties=parties;multi=require('../multiplayer')(api);api.multiplayer=multi;
 let g=parties.social(get(ps[0]),{action:'party_create',mode:'duo'}).party;assert.throws(()=>parties.social(get(ps[0]),{action:'party_invite',target:get(ps[3]).id}),/친구/);parties.social(get(ps[0]),{action:'party_invite',target:get(ps[1]).id});assert.throws(()=>parties.social(get(ps[2]),{action:'party_accept',partyId:g.id}),/유효/);parties.social(get(ps[1]),{action:'party_accept',partyId:g.id});parties.connect(ps[0]);assert.throws(()=>parties.queue(ps[0]),/모두/);parties.connect(ps[1]);assert.throws(()=>parties.queue(ps[1]),/팀장/);multi.action(ps[0],{action:'party_queue'});assert.equal(multi.queues.get('duo').length,2);assert.throws(()=>parties.social(get(ps[0]),{action:'party_leave'}),/먼저/);multi.action(ps[2],{action:'multi_queue',mode:'duo'});multi.action(ps[3],{action:'multi_queue',mode:'duo'});let r=[...multi.matches.values()][0];assert.equal(r.teams[r.players.indexOf(ps[0].id)],r.teams[r.players.indexOf(ps[1].id)]);r.phase='complete';r.sim=E.forArena(1400,950).create(r.players.map(()=> 'pizza'));r.sim.damage=r.players.map(()=>100);r.sim.winner=0;r.picks=r.players.map(()=> 'pizza');r.sim.actors.forEach((a,i)=>a.kills=i===0?1:0);multi.reward(r);const xp=get(ps[0]).season.xp;multi.reward(r);assert.equal(get(ps[0]).season.xp,xp);assert.equal(get(ps[0]).heroStats.pizza.plays,1);r.players.forEach(id=>multi.leave(sessions.get(id)));
 // Public rooms allow non-friends, reject full/locked rooms and stale IDs.
 const open=parties.social(get(ps[4]),{action:'party_create',mode:'duo'}).party;assert(parties.state(get(ps[5])).partyRooms.some(x=>x.id===open.id));parties.social(get(ps[5]),{action:'party_join',partyId:open.id});assert.equal(parties.membership.get(get(ps[5]).id),open.id);assert.throws(()=>parties.social(get(ps[6]),{action:'party_join',partyId:open.id}),/가득/);parties.social(get(ps[5]),{action:'party_leave'});ps[4].multiQueue='duo';assert(parties.state(get(ps[6])).partyRooms.find(x=>x.id===open.id).busy);assert.throws(()=>parties.social(get(ps[6]),{action:'party_join',partyId:open.id}),/매칭/);ps[4].multiQueue=null;parties.social(get(ps[4]),{action:'party_leave'});assert.throws(()=>parties.social(get(ps[6]),{action:'party_join',partyId:open.id}),/종료/);
 // Whole parties cancel together, and three two-player parties cannot be split into 3v3 teams.
 ps.slice(4,10).forEach((s,i)=>s.queuedGroup='pair'+Math.floor(i/2));assert.equal(multi.buildTeams(ps.slice(4,10).map(s=>s.id),3),null);ps[8].queuedGroup=null;ps[9].queuedGroup=null;const teams=multi.buildTeams(ps.slice(4,10).map(s=>s.id),3);assert(teams);assert.equal(teams[0],teams[1]);assert.equal(teams[2],teams[3]);
 parties.connect(ps[0]);parties.connect(ps[1]);multi.action(ps[0],{action:'party_queue'});multi.leave(ps[0]);assert.equal(multi.queues.get('duo').length,0);assert(events.some(e=>e.sid===ps[1].id&&e.event==='multi_left'));
 live=require('../live-features')(api);const c={id:'club',members:[get(ps[0]).id,get(ps[1]).id],name:'Club'};clans.set(c.id,c);for(const s of ps.slice(0,2))get(s).clanId=c.id;
 assert.throws(()=>live.action(ps[2],{action:'raid_start',hero:'pizza'}),/클럽/);assert.throws(()=>live.action(ps[0],{action:'raid_start',hero:'gymgay'}),/보유/);
 live.action(ps[0],{action:'raid_start',hero:'pizza'});let raid=live.raids.get(ps[0].id);assert(raid.sim.actors[1].raidBoss);assert.equal(get(ps[0]).raidAttempts,1);raid.sim.damage[0]=500;live.step(raid);assert.equal(c.raid.damage,500);live.step(raid);assert.equal(c.raid.damage,500);live.leave(ps[0]);assert.equal(live.raids.size,0);assert(saves>0);
 for(let i=0;i<2;i++){live.action(ps[0],{action:'raid_start',hero:'pizza'});live.leave(ps[0]);}assert.throws(()=>live.action(ps[0],{action:'raid_start',hero:'pizza'}),/3회/);
 c.raid.damage=10000;c.raid.contributions[get(ps[0]).id]=500;live.reward(c);live.reward(c);assert.equal(get(ps[0]).mail.filter(m=>m.id.startsWith('raid:')).length,2);assert.equal(get(ps[1]).mail.filter(m=>m.id.startsWith('raid:')).length,0);c.raid.contributions[get(ps[1]).id]=1;live.reward(c);assert.equal(get(ps[1]).mail.filter(m=>m.id.startsWith('raid:')).length,2);
 // Only friends may watch; a watcher has no player slot and cleans up when target finishes.
 const target=ps[1];target.room='watchroom';rooms.set(target.room,{phase:'battle',players:[ps[1].id,ps[2].id],sim:E.create(['pizza','rico'])});live.action(ps[0],{action:'spectate',target:get(target).id});assert(live.watchers.has(ps[0].id));assert(events.some(e=>e.event==='spectate_start'&&e.state.actors[0].sid===target.id));assert(!ps[0].room&&!ps[0].multi);assert.throws(()=>live.action(ps[3],{action:'spectate',target:get(target).id}),/친구/);const w=live.watchers.get(ps[0].id);rooms.get(target.room).phase='complete';w.timer.fn();assert.equal(live.watchers.size,0);assert(w.timer.closed);assert(events.some(e=>e.event==='spectate_end'));
}finally{global.setInterval=oldSI;global.setTimeout=oldST;global.clearInterval=oldCI;global.clearTimeout=oldCT;}
console.log('PASS: 36 title mappings, 1000 threshold, mailbox claim/equip, 300 trophy pins and removed borders, match-only stats, first win cap/idempotency, party friendship/team packing/cancellation, server raid damage/attempts/rewards, private read-only spectating/cleanup');
