'use strict';
const assert=require('node:assert/strict'),E=require('../engine'),factory=require('../multiplayer'),heroes=E.HEROES;
const progression=require('../progression').create(heroes),season=require('../season').create(heroes),sessions=new Map(),profiles=new Map(),events=[],jobs=[];let saves=0;
const realInterval=global.setInterval,realTimeout=global.setTimeout;global.setInterval=fn=>{jobs.push(fn);return {}};global.setTimeout=fn=>{jobs.push(fn);return {}};
const api={sessions,profiles,profile:s=>s&&profiles.get(s.profile),send:(s,event,payload)=>{if(s)events.push({sid:s.id,event,...payload})},migrate:u=>{progression.migrate(u);season.migrate(u);return u},persist:()=>saves++,progression,season,contribution:u=>u.contribution=(u.contribution||0)+1,publicUser:u=>({nick:u.nick,totalTrophies:progression.total(u)}),offer:u=>u.owned.slice(0,3),exitOther:s=>multi.leave(s),engine:E,cosmetics:{emote:()=>({id:'test'})}};
const multi=factory(api);
function player(i){let u={id:'u'+i,tag:'ABCD'+String(i).padStart(4,'0'),nick:'User '+i,coins:0,wins:0,owned:['pizza','rico','lea'],levels:{pizza:i===0?5:0},trophies:{pizza:i*10}};api.migrate(u);profiles.set(u.id,u);const s={id:'session'+i,profile:u.id,stream:{destroyed:false}};sessions.set(s.id,s);return s;}
const ps=Array.from({length:12},(_,i)=>player(i));
function enqueue(mode,players){players.forEach(s=>multi.action(s,{action:'multi_queue',mode}));return [...multi.matches.values()].at(-1);}
function ready(r){for(const id of r.players)multi.action(sessions.get(id),{action:'multi_ready',hero:'pizza',angle:0});assert.equal(r.phase,'battle');}
let r=enqueue('duo',ps.slice(0,4));assert.equal(r.players.length,4);assert.deepEqual([r.teams.filter(t=>t===0).length,r.teams.filter(t=>t===1).length],[2,2]);assert.equal(events.filter(e=>e.event==='multi_matched').length,4);assert.throws(()=>multi.action(ps[0],{action:'multi_queue',mode:'trio'}),/진행 중/);assert.throws(()=>multi.action(ps[0],{action:'multi_ready',hero:'gymgay',angle:0}),/보유/);ready(r);assert.equal(r.sim.actors[0].level,5);
// Friendly fire and enemy-only targeting, including projectile and area effects.
const a=E.forArena(1400,950),sim=a.create(['lea','pizza','rico','pizza'],[0,0,0,0],12);sim.teams=[0,0,1,1];sim.manualUlt=[true,true,true,true];sim.actors.forEach(f=>{f.atkTimer=999;f.invul=0;f.vx=f.vy=0;f.ultTimer=999;f.x=400;f.y=400;});sim.actors[2].x=1000;sim.actors[3].x=1100;const allyHP=sim.actors[1].hp;for(let n=0;n<20;n++)a.tick(sim,.05);assert.equal(sim.actors[1].hp,allyHP);assert(!sim.actors[1].forceHold);sim.actors[0].ultTimer=0;assert(a.useUltimate(sim,0));assert.equal(sim.actors[0].targetSide,2);
const project=a.create(['pizza','pizza','pizza','pizza'],[],11);project.teams=[0,0,1,1];project.manualUlt=[true,true,true,true];project.actors.forEach(f=>{f.atkTimer=999;f.vx=f.vy=0;f.ultTimer=999;});project.actors[0].x=200;project.actors[1].x=300;project.actors[2].x=900;project.actors[3].x=1000;project.actors.forEach(f=>f.y=400);project.bullets.push({type:'gum',owner:0,x:300,y:400,vx:0,vy:0,r:10,damage:30,life:5,age:0});a.tick(project,.05);assert.equal(project.actors[1].hp,project.actors[1].max);
const winners=r.teams[0];for(const f of r.sim.actors)if(f.team!==winners)f.hp=0;multi.step(r);assert.equal(r.phase,'complete');const coins=r.players.map(id=>api.profile(sessions.get(id)).coins);assert(coins.every((c,i)=>c===(r.teams[i]===winners?50:0)));for(let i=0;i<4;i++){const u=profiles.get(r.profiles[i]);assert.equal(u.season.xp,r.teams[i]===winners?50:0);assert.equal(u.trophies.pizza,i*10+(r.teams[i]===winners?10:0));}multi.reward(r);assert.deepEqual(r.players.map(id=>api.profile(sessions.get(id)).coins),coins);
r=enqueue('trio',ps.slice(4,10));assert.deepEqual([r.teams.filter(t=>t===0).length,r.teams.filter(t=>t===1).length],[3,3]);ready(r);const own=r.teams[0];r.sim.actors.forEach(f=>{if(f.team===own)f.hp=0});multi.step(r);assert.equal(r.phase,'complete');r.players.forEach((id,i)=>assert.equal(api.profile(sessions.get(id)).coins,r.teams[i]===own?0:50));
// Same account cannot occupy multiple slots; mode queues remain separate and cancellable.
multi.action(ps[10],{action:'multi_queue',mode:'duo'});assert.equal(multi.counts().queues.duo,1);const copy={id:'anotherSession',profile:ps[10].profile,stream:{}};sessions.set(copy.id,copy);assert.throws(()=>multi.action(copy,{action:'multi_queue',mode:'duo'}),/이미 매칭/);multi.action(ps[11],{action:'multi_queue',mode:'trio'});assert.equal(multi.counts().queues.trio,1);multi.leave(ps[10]);multi.leave(ps[11]);assert.equal(multi.counts().queues.duo,0);
r=enqueue('royale4',ps.slice(0,4));ready(r);r.sim.actors.forEach(f=>{f.hp=0});r.sim.actors[0].hp=100;r.sim.eliminations=[3,2,1];r.sim.finished=true;r.sim.winner=0;const before=r.players.map(id=>({coins:api.profile(sessions.get(id)).coins,t:api.profile(sessions.get(id)).trophies.pizza}));multi.step(r);for(let i=0;i<4;i++){const u=profiles.get(r.profiles[i]),prize=factory.ROYALE_REWARDS[i+1];assert.equal(u.coins-before[i].coins,prize.coins);assert.equal(u.trophies.pizza-before[i].t,prize.trophies);assert.equal(r.rewards[r.players[i]].rank,i+1);}const prev=saves;multi.reward(r);assert.equal(saves,prev);multi.resume(ps[0]);assert.equal(events.at(-1).event,'multi_end');assert.equal(events.at(-1).reward.trophies,13);
// In pick phase a departure cancels the match without rewards.
r=enqueue('duo',ps.slice(0,4));multi.leave(ps[0]);assert(!multi.matches.has(r.id));assert(events.some(e=>e.event==='multi_cancelled'));r=enqueue('duo',ps.slice(0,4));ready(r);const losing=r.teams[0];for(const id of [...r.players].filter((id,i)=>r.teams[i]===losing))multi.leave(sessions.get(id));assert.equal(r.phase,'complete');assert(r.forfeit);assert(r.players.filter((id,i)=>r.teams[i]!==losing).every(id=>r.rewards[id].xp===0));
// Timeout counts total team health; one eliminated teammate doesn't end the match.
const timeout=a.create(['pizza','pizza','pizza','pizza'],[],77);timeout.teams=[0,0,1,1];timeout.manualUlt=[true,true,true,true];timeout.actors[0].hp=0;timeout.actors[1].hp=timeout.actors[1].max;timeout.actors[2].hp=timeout.actors[2].max*.8;timeout.actors[3].hp=timeout.actors[3].max*.8;a.tick(timeout,.05);assert(!timeout.finished);timeout.t=130;a.tick(timeout,.05);assert(timeout.finished);assert.equal(timeout.teams[timeout.winner],1);
for(const m of multi.matches.values())multi.leave(sessions.get(m.players[0]));global.setInterval=realInterval;global.setTimeout=realTimeout;
console.log('PASS: 2v2/3v3/royale4 queues, team sizes, levels, ally protections, awards exactly once, ranks 13/7/2/0, coins 50/30/10/0, resume, invalid ownership, duplicate accounts, cancels, forfeits, team timeout');
