const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const crypto=require('node:crypto');
(async()=>{
 const src=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');
 const boot=src.lastIndexOf('initStorage().then(');
 assert(boot>0,'server boot statement found');
 const ctx={require,__dirname:path.join(__dirname,'..'),process:{env:{},on(){}},console:{log(){},error(){}},setInterval(){return {unref(){}}},setTimeout,Buffer};
 vm.createContext(ctx);
 vm.runInContext(src.slice(0,boot),ctx,{filename:'server.js',timeout:10000});
 const a='a'.repeat(24), b='b'.repeat(64);
 const saved={id:a,secret:b,tag:'AB12CD34',nick:'기존 유저',avatar:'moai',coins:900,wins:12,losses:3,owned:['moai','pogo','rico'],friends:['some-friend'],requests:[],setupDone:true};
 let snapshots=[[saved]],writes=0;
 ctx.mockPool={async query(sql,args){
   if(sql.includes('SELECT data FROM ball_battle_backups'))return {rows:snapshots.map(data=>({data}))};
   if(sql.includes('INSERT INTO ball_battle_state')){writes++;return {rowCount:1}};
   throw Error('Unexpected SQL: '+sql);
 }};
 vm.runInContext('dbPool=mockPool',ctx);
 const p=vm.runInContext('profiles',ctx);
 const {recoverOldProfile,getProfile}=vm.runInContext('({recoverOldProfile,getProfile})',ctx);
 assert.equal(p.size,0);
 let u=await recoverOldProfile(a,b);
 assert.equal(u.nick,'기존 유저');assert.equal(u.coins,900);
 assert.equal(u.owned.length,3);assert.equal(u.wins,12);
 assert.equal(getProfile({id:a,secret:b}).tag,'AB12CD34');
 await assert.rejects(()=>recoverOldProfile(a,'c'.repeat(64)),e=>e.code==='PROFILE_SECRET_MISMATCH');
 assert.equal(p.get(a).coins,900,'bad secret must never overwrite data');
 const unknownId='d'.repeat(24), unknownSecret='e'.repeat(64);
 u=await recoverOldProfile(unknownId,unknownSecret);
 assert.equal(u.id,unknownId);assert.equal(u.secret,unknownSecret);
 assert.equal(u.owned.length,3);assert.equal(u.coins,0);
 assert.equal(p.get(a).coins,900,'re-register does not affect other profiles');
 await assert.rejects(()=>recoverOldProfile('invalid',unknownSecret),e=>e.code==='PROFILE_CREDENTIALS_INVALID');
 // A stolen or outdated key must not recover a user even when that user is only in backups.
 const blockedId='f'.repeat(24);
 snapshots=[[{...saved,id:blockedId,tag:'FFEEDDCC'}]];
 await assert.rejects(()=>recoverOldProfile(blockedId,'0'.repeat(64)),e=>e.code==='PROFILE_SECRET_MISMATCH');
 assert(!p.has(blockedId));
 await vm.runInContext('dbSaveChain',ctx);
 assert(writes>=2,'restorations persisted');
 const html=fs.readFileSync(path.join(__dirname,'..','game.html'),'utf8');
 const scripts=html.split('<script>').slice(1).map(v=>v.split('</script>')[0]);
 assert.equal(scripts.length,2,'expected engine and UI scripts');
 scripts.forEach(src=>{new Function(src);});
 assert(html.includes('profileAuthHelp(e)'));
 console.log('PASS existing data recovery, secret protection, missing accounts, SQL writes, HTML syntax');
})().catch(e=>{console.error(e);process.exitCode=1});
