'use strict';
const assert=require('node:assert/strict');
const E=require('../engine.js');
const fs=require('node:fs');
const s=E.create(['filter','pizza'],[0,0],4921);
const f=s.actors[0],op=s.actors[1];
f.ultTimer=999;op.ultTimer=999;op.atkTimer=999;
for(let i=0;i<420&&!s.finished;i++)E.tick(s,1/60);
const active=()=>s.bullets.filter(b=>b.type==='filterpoop'&&b.owner===0);
const before=active().length;
assert(before>=5, 'one new bouncing poop every second (7s has at least 5)');
assert(f.atkTimer<=1.1,'Filter attack interval should be one second');
assert(active().every(b=>b.bounces>0),'poop must persist and bounce');
f.ultTimer=-1;E.tick(s,1/60);
const after=active().length;
assert(after>=before,'Filter ultimate must not remove poop projectiles');
assert(s.fx.some(x=>x.type==='poopBurst'),'poop explosions must be visually animated');
for(let i=0;i<35&&!s.finished;i++)E.tick(s,1/60);
assert(active().length>=after,'poop must reappear/continue existing after blast');
const client=fs.readFileSync(__dirname+'/../game.html','utf8');
assert(client.includes("drawProp('hand'"),'animated hand prop');
assert(client.includes("drawProp('bat'"),'animated bat prop');
assert(client.includes("drawProp('bin'"),'trash can visible while trapped');
assert(client.includes("drawProp('foot'"),'kick animation');
assert(client.includes("drawProp('blade'"),'sword slash animation');
assert(client.includes("drawProp('clap'"),'clap animation');
assert(client.includes("ctx.imageSmoothingQuality='high'"),'render high quality sprite interpolation');
for(const js of client.split('<script>').slice(1).map(x=>x.split('</script>')[0]))new Function(js);
console.log('PASS 1s new poop, persistent poop after super, prop animation, high-detail rendering and client scripts');
