'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
// Expose the engine's automatic attack dispatch in a test-only VM.
const env={module:{exports:{}}};vm.createContext(env);
vm.runInContext(fs.readFileSync('engine.js','utf8').replace('return {HEROES,HERO_BY_ID,create,tick,W,H,','return {_basic:basic,_super:superMove,_damage:damage,HEROES,HERO_BY_ID,create,tick,W,H,'),env);
const E=env.module.exports;
const make=(id,enemy='pizza')=>{const s=E.create([id,enemy]);for(const f of s.actors){f.atkTimer=100;f.ultTimer=100;f.vx=f.vy=0;}return s;};
const advance=(s,seconds)=>{for(let t=0;t<seconds-1e-8&&!s.finished;t+=.05)E.tick(s,.05);};
assert.equal(E.HEROES.length,27);assert(Math.abs(E.HERO_BY_ID.moai.hp-129*.6)<1e-9);
let s=make('medicine');E._basic(s,...s.actors);advance(s,.35);assert.equal(s.bullets.filter(p=>p.type==='pill').length,9,'3 pills in each of 3 bursts');
s=make('medicine');E._super(s,...s.actors);assert.equal(s.bullets.length,12);const p=s.bullets[0],target=s.actors[1];target.x=p.x;target.y=p.y;target.stun=5;let hp=target.hp;E.tick(s,.01);assert(target.hp<hp,'outbound damage');p.age=.7;p.x=target.x;p.y=target.y;p.vx=p.vy=0;hp=target.hp;E.tick(s,.01);assert(target.hp<hp,'return damage on same enemy');hp=target.hp;E.tick(s,.01);assert.equal(target.hp,hp,'one hit per return pass');assert(s.bullets.includes(p),'pill survives enemy contact');
s=make('alvin');s.actors[1].x=s.actors[0].x+180;E._basic(s,...s.actors);assert.equal(s.actors[1].hp,162);E._super(s,...s.actors);assert.equal(s.bullets.filter(p=>p.type==='longsword').length,12);
s=make('lea');s.actors[1].x=s.actors[0].x+120;advance(s,.5);assert(s.actors[1].hp<166,'continuous forcefield');E._super(s,...s.actors);assert.equal(s.actors[0].morphId,'pizza');E._basic(s,...s.actors);assert.equal(s.bullets.at(-1).damage,12);advance(s,5.05);assert.equal(s.actors[0].morphId,null,'revert after 5 seconds');
s=make('lea','sahur');s.actors[1].x=s.actors[0].x+130;E._super(s,...s.actors);E._basic(s,...s.actors);E.tick(s,.05);assert(s.actors[1].hp<=162,'copied melee deals 1.5x 8 damage');
s=make('pogo6974');E._basic(s,...s.actors);assert.equal(s.bullets.length,12);E._super(s,...s.actors);assert.equal(s.zones.length,1);const z=s.zones[0];s.actors[1].x=z.x+z.w/2;s.actors[1].y=z.y+z.h/2;assert(!s.actors[1].cornerTrap,'entering later does not trap');hp=s.actors[1].hp;advance(s,.2);assert(s.actors[1].hp<hp);advance(s,6);assert.equal(s.zones.length,1,'zone persists past 5 seconds');
// Same seed casts into same corner: trap only enemies present when casting.
s=make('pogo6974');const probe=make('pogo6974');E._super(probe,...probe.actors);const corner=probe.zones[0];s.actors[1].x=corner.x+corner.w/2;s.actors[1].y=corner.y+corner.h/2;E._super(s,...s.actors);assert(s.actors[1].cornerTrap);s.actors[1].vx=1000;advance(s,.5);assert(s.actors[1].x<=corner.x+corner.w-39);advance(s,4.6);assert(!s.actors[1].cornerTrap,'trap expires');
s=make('zetaseungju');E._basic(s,...s.actors);assert.equal(s.bullets.length,5);const before=s.bullets[0].vy;E.tick(s,.05);assert.notEqual(s.bullets[0].vy,before,'kiss curves');E._super(s,...s.actors);assert.equal(s.actors[0].stealth,5);s.bullets=[];s.actors[1].x=s.actors[0].x+60;hp=s.actors[1].hp;E.tick(s,.01);assert(s.actors[1].hp<=hp-32);assert.equal(s.actors[0].stealth,0);
s=make('b67');s.actors[0].hp=100;E._basic(s,...s.actors);assert.equal(s.bullets[0].type,'number67');E._super(s,...s.actors);assert.equal(s.clones.length,2);assert(s.clones.every(q=>q.hp===20));assert.equal(s.actors.length,2);E._damage(s,s.clones[0],100,s.actors[1]);assert(!s.finished,'clone death does not finish match');advance(s,1);assert.equal(s.clones.length,1);assert(s.fx.some(f=>f.type==='shot'&&f.t>0)&&s.clones[0].atkTimer<.65,'clones attack automatically');
const R=require('../royale');for(let n=3;n<=10;n++){const r=R.create(Array.from({length:n},(_,i)=>({sid:'p'+i,nick:'p'+i,hero:E.HEROES[21+i%6].id})),n);for(let t=0;t<2700&&!r.finished;t++)R.tick(r,.05);assert(r.finished);assert.equal(r.placements.length,n);assert.equal(new Set(r.placements.map(q=>q.sid)).size,n);}
const html=fs.readFileSync('game.html','utf8');assert(html.includes(fs.readFileSync('engine.js','utf8')),'offline engine stays identical');for(const id of ['medicine','alvin','lea','pogo6974','zetaseungju','b67']){assert(html.includes('"'+id+'":"data:image/jpeg;base64,'));assert(fs.readFileSync('portraits/'+id+'.jpg').length>2700);}
console.log('PASS six character abilities, Moai 60% HP, copied melee/projectiles, returning hits, corner duration/traps, stealth, clone ownership and royale ranks');
