'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const env={module:{exports:{}}};vm.createContext(env);vm.runInContext(fs.readFileSync('engine.js','utf8').replace('return {HEROES,HERO_BY_ID,create,tick,W,H,','return {_basic:basic,_super:superMove,_updateSuper:updateSuper,HEROES,HERO_BY_ID,create,tick,W,H,'),env);const E=env.module.exports;
function make(id,other='pizza'){const s=E.create([id,other]);for(const f of s.actors){f.atkTimer=f.ultTimer=100;f.vx=f.vy=0;}return s;}
function advance(s,t){for(let i=0;i<Math.round(t/.01)&&!s.finished;i++)E.tick(s,.01);}
let s=make('b67');s.actors[0].hp=50;E._super(s,...s.actors);assert.equal(s.clones.length,2);assert(s.clones.every(q=>q.hp===32.6&&q.max===32.6));E._basic(s,s.clones[0],s.actors[1]);assert(Math.abs(s.bullets[0].damage-1.56)<1e-9);
s=make('alvin');E._super(s,...s.actors);for(let i=0;i<140;i++)E._updateSuper(s,...s.actors,.01);assert.equal(s.bullets.length,60);assert.equal(s.actors[0].ultActive,null);for(let i=0;i<20;i++)E._updateSuper(s,...s.actors,.05);assert.equal(s.bullets.length,60,'exactly five waves');
s=make('spyger');E._basic(s,...s.actors);let p=s.bullets[0];assert(p.homing);s.actors[1].y=500;let before=Math.atan2(p.vy,p.vx),speed=Math.hypot(p.vx,p.vy);E.tick(s,.05);assert(Math.atan2(p.vy,p.vx)>before,'tracks moving enemy');assert(Math.abs(Math.hypot(p.vx,p.vy)-speed)<1e-8);
s=make('pogo6974');E._basic(s,...s.actors);assert.equal(s.bullets.length,16);assert(s.bullets.every(p=>p.damage===3.65*1.25));E._super(s,...s.actors);assert.equal(s.zones[0].w,(E.W-44)*.39);assert.equal(s.zones[0].h,(E.H-44)*.435);
s=make('icecookie');s.actors[1].x=400;E._super(s,...s.actors);s.actors[0].stun=10;s.actors[1].stun=10;let hp=s.actors[1].hp;advance(s,3.29);assert.equal(s.actors[1].hp,hp,'no early shatter damage');advance(s,.02);assert.equal(s.actors[1].hp,hp-30);advance(s,.2);assert.equal(s.actors[1].hp,hp-30,'shatters only once');assert(s.fx.some(f=>f.type==='iceShatter'));
for(const ids of [['lea','pizza'],['pizza','lea']]){s=make(...ids);const lea=s.actors.find(f=>f.id==='lea'),victim=s.actors.find(f=>f.id==='pizza');lea.x=400;victim.x=570;victim.y=lea.y;victim.vx=200;victim.atkTimer=victim.ultTimer=0;E.tick(s,.01);assert(victim.forceHold);let until=victim.forceHold.until;advance(s,1.9);assert.equal(victim.forceHold.until,until,'duration does not refresh every tick');assert(!s.bullets.some(p=>p.owner===victim.side),'cannot attack or cast');assert(Math.hypot(victim.x-lea.x,victim.y-lea.y)<155,'pulled inside field');assert(victim.hp<160,'takes continuous damage');advance(s,.12);assert(!victim.forceHold,'released after 2 seconds');assert(s.fx.some(f=>f.type==='shot'&&f.side===victim.side&&f.t>=until),'can attack after release');}
const html=fs.readFileSync('game.html','utf8');assert(html.includes(fs.readFileSync('engine.js','utf8')));const script=html.match(/function sortedClanMembers[\s\S]*?\nasync function renderClans/)[0].replace(/\nasync function renderClans$/,'');const c={};vm.createContext(c);vm.runInContext(script,c);c.rows=[{nick:'a',wins:1,coins:100},{nick:'b',wins:3,coins:10},{nick:'c',wins:2,coins:50}];assert.equal(vm.runInContext("sortedClanMembers(rows,'wins')[0].nick",c),'b');assert.equal(vm.runInContext("sortedClanMembers(rows,'coins')[0].nick",c),'a');assert.equal(c.rows[0].nick,'a');assert(html.includes('id="clanMemberSort"'));assert(fs.readFileSync('server.js','utf8').includes('tag:u.tag,wins:u.wins||0,coins:u.coins||0'));
// Determinism and termination in the shared server/offline/royale engine.
for(const id of ['lea','alvin','spyger','pogo6974','icecookie','b67']){const a=E.create([id,'pizza'],[0,0],33),b=E.create([id,'pizza'],[0,0],33);for(let t=0;t<1100&&!a.finished;t++){E.tick(a,.05);E.tick(b,.05);}assert(a.finished);assert.equal(JSON.stringify(a),JSON.stringify(b));assert(a.actors.every(f=>Number.isFinite(f.hp)&&f.hp>=0));}
console.log('PASS v11.3 clone scaling, 5 volleys, homing, spikes/range, timed shatter, 2-second capture, member sorting and determinism');
