'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const ctx={module:{exports:{}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('engine.js','utf8').replace('return {HEROES,HERO_BY_ID,create,tick,W,H,','return {_basic:basic,_super:superMove,_updateSuper:updateSuper,HEROES,HERO_BY_ID,create,tick,W,H,'),ctx);const E=ctx.module.exports;
function make(id){const s=E.create([id,'pizza']);for(const f of s.actors){f.atkTimer=f.ultTimer=100;f.vx=f.vy=0;f.contact=100;}return s;}
function advance(s,t){for(let i=0;i<Math.round(t/.01)&&!s.finished;i++)E.tick(s,.01);}
let s=make('pogo6974');E._basic(s,...s.actors);assert(s.bullets.every(p=>p.damage===3.65*1.25));
s=make('spyger');E._basic(s,...s.actors);assert.equal(s.bullets[0].damage,9);assert(s.bullets[0].homing);s.bullets=[];E._super(s,...s.actors);const u=s.actors[0].ultActive;s.actors[1].x=u.x-240;let hp=s.actors[1].hp;E._updateSuper(s,...s.actors,.25);assert.equal(s.actors[1].hp,+(hp-.875).toFixed(2),'expanded radius hits at 240');s.actors[1].x=u.x-270;hp=s.actors[1].hp;E._updateSuper(s,...s.actors,.25);assert.equal(s.actors[1].hp,hp,'outside new radius is safe');
s=make('hoit');E._super(s,...s.actors);let orb=s.bullets[0];assert.equal(orb.life,6);s.actors[1].x=orb.x;s.actors[1].y=orb.y;s.actors[0].stun=s.actors[1].stun=10;hp=s.actors[1].hp;E.tick(s,.01);assert.equal(s.actors[1].hp,hp-10);assert(s.bullets.includes(orb),'orb persists after impact');orb.x=s.actors[1].x;orb.y=s.actors[1].y;orb.vx=orb.vy=0;hp=s.actors[1].hp;E.tick(s,.01);assert(s.actors[1].hp>hp-1,'no repeated impact burst');advance(s,3.05);assert(s.bullets.includes(orb),'remains beyond old 3-second limit');advance(s,2.95);assert(!s.bullets.includes(orb),'expires after 6 seconds');
s=make('pizza');E._super(s,...s.actors);hp=s.actors[1].hp;E._updateSuper(s,...s.actors,2.25);assert.equal(s.actors[1].hp,hp-24);assert.equal(s.actors[0].ultActive,null);
s=make('b67');E._super(s,...s.actors);assert(s.clones.every(c=>c.hp===32.6));E._basic(s,s.clones[0],s.actors[1]);assert.equal(s.bullets[0].damage,1.56,'clone attack remains 30 percent');
s=make('utti');s.actors[1].stun=10;E._super(s,...s.actors);advance(s,.03);assert(s.fx.some(f=>f.type==='number'&&f.label==='체공 충돌'),'contact during super applies actual damage');const contactHp=s.actors[1].hp;advance(s,.5);assert.equal(s.actors[1].hp,contactHp,'contact rate limited');advance(s,.3);assert(s.actors[1].hp<contactHp,'can hit again after cooldown');assert(s.actors[0].airborne>0);
const html=fs.readFileSync('game.html','utf8');assert(html.includes(fs.readFileSync('engine.js','utf8')));assert(html.includes('id="royaleReplayBtn"'));assert(html.includes("await sendAction('royale_replay')"));
console.log('PASS v11.5 original 1.25x spikes, homing damage, expanded zone, persistent 6-second orb, airborne collision cooldown, clone HP nerf, pizza damage');
