'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const ctx={module:{exports:{}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('engine.js','utf8').replace('return {HEROES,HERO_BY_ID,create,tick,W,H,','return {_basic:basic,_super:superMove,_updateSuper:updateSuper,HEROES,HERO_BY_ID,create,tick,W,H,'),ctx);const E=ctx.module.exports;
function make(id){const s=E.create([id,'pizza']);for(const f of s.actors){f.atkTimer=f.ultTimer=100;f.vx=f.vy=0;f.contact=100;}return s;}
let s=make('spyger');E._basic(s,...s.actors);assert.equal(s.bullets[0].damage,8);assert(s.bullets[0].homing);
s=make('rico');E._basic(s,...s.actors);assert.equal(s.bullets.length,2);assert(s.bullets.every(p=>p.damage===2.8));s.bullets=[];E._super(s,...s.actors);E._updateSuper(s,...s.actors,.6);assert.equal(s.bullets.length,18);assert(s.bullets.every(p=>p.damage===2.6));
for(const hp of [120,1]){s=make('moai');s.actors[1].hp=hp;E._super(s,...s.actors);assert.equal(s.actors[1].hp,hp*.5);assert(!s.finished,'half health remains even at low HP');}
s=make('sahur');E._super(s,...s.actors);E._updateSuper(s,...s.actors,5.1);assert.equal(s.actors[1].hp,160,'ultimate damage halves to 8 total');assert.equal(s.actors[0].ultActive,null);
s=make('filter');E._basic(s,...s.actors);let poop=s.bullets[0];assert.equal(poop.r,17*1.5);assert.equal(poop.damage,1.5);s.actors[1].x=poop.x;s.actors[1].y=poop.y;E._super(s,...s.actors);assert.equal(s.actors[1].hp,162.5);assert(s.bullets.includes(poop),'explosion preserves permanent poop');
s=make('pizza');E._basic(s,...s.actors);let p=s.bullets[0];assert.equal(p.life,5);assert.equal(p.turnRate,.65);assert(p.homing);s.actors[1].x=p.x-200;s.actors[1].y=p.y-150;let angle=Math.atan2(p.vy,p.vx);E.tick(s,.05);const difference=Math.atan2(Math.sin(Math.atan2(p.vy,p.vx)-angle),Math.cos(Math.atan2(p.vy,p.vx)-angle));assert(Math.abs(difference)<=.65*.05+1e-8,'weak steering cannot snap to evading target');assert.equal(s.actors[1].hp,168,'moving away dodges projectile');for(const f of s.actors)f.invul=10;for(let i=0;i<495;i++)E.tick(s,.01);assert(s.bullets.includes(p),'pizza survives wall bounces almost 5 seconds');E.tick(s,.02);assert(!s.bullets.includes(p),'pizza expires at 5 seconds');
s=make('eggkimchi');s.actors[1].x=s.actors[0].x+250;E._basic(s,...s.actors);E.tick(s,.01);assert.equal(s.actors[1].hp,161,'slap hits inside buffed 260 range');s=make('eggkimchi');s.actors[1].x=s.actors[0].x+280;E._basic(s,...s.actors);E.tick(s,.01);assert.equal(s.actors[1].hp,168,'outside range still misses');
const h=fs.readFileSync('game.html','utf8');assert(h.includes(fs.readFileSync('engine.js','utf8')));assert(h.includes("ctx.font=(b.r*29/17)+'px sans-serif'"),'visible poop scales with actual hitbox');
console.log('PASS v11.6 damage balance, exact Moai half health, weak steer/dodge and 5-second pizza, larger permanent poop, real slap range');
