'use strict';
const assert=require('node:assert/strict'),E=require('../engine'),P=require('../progression'),fs=require('node:fs'),vm=require('node:vm');
const p=P.create(E.HEROES),ids=E.HEROES.map(h=>h.id),user=(tag='11111111')=>({id:tag,tag,nick:tag,secret:'test-secret',coins:11500,owned:[ids[0]],wins:12,trophies:{},levels:{}});
const u=user();p.migrate(u);for(let i=0;i<5;i++){p.action(u,{action:'upgrade',hero:ids[0],expectedLevel:i});assert.equal(u.levels[ids[0]],i+1)}assert.equal(u.coins,0);assert.throws(()=>p.action(u,{action:'upgrade',hero:ids[0],expectedLevel:5}),/최대/);assert.throws(()=>p.action(u,{action:'upgrade',hero:ids[1],expectedLevel:0}),/보유/);
const stale=user();p.action(stale,{action:'upgrade',hero:ids[0],expectedLevel:0});assert.throws(()=>p.action(stale,{action:'upgrade',hero:ids[0],expectedLevel:0}),/레벨 정보/);assert.equal(stale.coins,11000);stale.coins=0;assert.throws(()=>p.action(stale,{action:'upgrade',hero:ids[0],expectedLevel:1}),/부족/);
const a=user(P.ADMIN_TAG),b=user('22222222'),people=new Map([a,b,u].map(x=>[x.id,x]));p.migrate(a);assert.equal(a.owned.length,ids.length);assert(ids.every(id=>a.levels[id]===5));p.migrate(a);assert.equal(a.mail.length,2);const launch=a.mail.find(m=>m.id==='mobile-app-release-v1');assert.equal(launch.title,'모바일 앱 출시!');assert.equal(launch.read,false);p.action(a,{action:'mail_read',mailId:launch.id});p.migrate(a);assert.equal(a.mail.filter(m=>m.id===launch.id).length,1);assert.equal(launch.read,true);assert.equal(a.wins,12);assert.equal(a.coins,11500);
const gift={action:'admin_send',scope:'one',tag:b.tag,coins:123,heroes:[ids[1]],requestId:'gift-request-123',title:'테스트',body:'보상'};assert.throws(()=>p.action(b,gift,people),/관리자/);b.isAdmin=true;assert(!p.privateFields(b).isAdmin);assert.throws(()=>p.action(b,{action:'admin_users'},people),/관리자/);assert.equal(p.action(a,gift,people).sent,1);const mail=b.mail[0];assert.equal(b.coins,11500);assert.equal(p.action(a,gift,people).duplicate,true);assert.equal(b.mail.filter(m=>m.id===mail.id).length,1);assert.throws(()=>p.action(a,{...gift,coins:124},people),/중복/);assert.throws(()=>p.action(u,{action:'mail_claim',mailId:mail.id},people),/우편/);p.action(b,{action:'mail_claim',mailId:mail.id},people);p.action(b,{action:'mail_claim',mailId:mail.id},people);assert.equal(b.coins,11623);assert(b.owned.includes(ids[1]));assert(mail.read&&mail.claimed);assert.equal(p.action(a,{...gift,scope:'all',requestId:'all-request-123'},people).sent,3);
for(let n=1;n<=5;n++){const v=user();const history=ids.slice(0,n).map((hero,i)=>({hero,won:i===n-1}));const rewards=p.trophies(v,history);assert.equal(rewards.reduce((s,x)=>s+x.amount,0),10);assert.equal(p.total(v),10);if(n===3)assert.equal(rewards[2].amount,4)}
const tie=user();assert.deepEqual(p.trophies(tie,ids.slice(0,3).map(hero=>({hero,won:true}))).map(x=>x.amount),[4,3,3]);const repeated=user();assert.deepEqual(p.trophies(repeated,[{hero:ids[0],won:false},{hero:ids[0],won:true},{hero:ids[1],won:true}]).map(x=>x.amount),[5,5]);
const engineSrc=fs.readFileSync(require.resolve('../engine'),'utf8').replace('return {HEROES,HERO_BY_ID,create,tick,W,H,forArena:','return {basic,damage,HEROES,HERO_BY_ID,create,tick,W,H,forArena:');const ctx={module:{exports:{}},console};vm.runInNewContext(engineSrc,ctx);const X=ctx.module.exports;const s=X.create(['pizza','pizza'],[0,0],1,[5,0]);assert.equal(s.actors[0].hp,2*E.HERO_BY_ID.pizza.hp);X.basic(s,s.actors[0],s.actors[1]);const z=X.create(['pizza','pizza']);X.basic(z,z.actors[0],z.actors[1]);assert.equal(s.bullets[0].damage,z.bullets[0].damage*2);let before=s.actors[1].hp;X.damage(s,s.actors[1],5,s.actors[0],'direct');assert.equal(before-s.actors[1].hp,10);before=s.actors[1].hp;X.damage(s,s.actors[1],5,s.actors[0],'projectile',true);assert.equal(before-s.actors[1].hp,5);before=s.actors[1].hp;X.damage(s,s.actors[1],before*.5,s.actors[0],'남은 체력 50% 감소');assert.equal(s.actors[1].hp,+(before*.5).toFixed(2));
console.log('v12 progression: costs, authorization, idempotent gifts/claims, exact trophies and combat scaling passed');
