'use strict';
const assert=require('node:assert/strict'),E=require('../engine'),P=require('../progression'),S=require('../season');
const ids=E.HEROES.map(h=>h.id),progress=P.create(E.HEROES),season=S.create(E.HEROES),user=(tag='11111111')=>({id:tag,tag,nick:tag,coins:0,owned:['pizza'],levels:{},trophies:{}});
let u=user();season.migrate(u);for(let i=0;i<60;i++)season.record(u,[{hero:ids[i%ids.length]}],true);assert.equal(u.season.xp,3000);assert.equal(season.fields(u).seasonPass.tier,30);season.record(u,[],true);assert.equal(u.season.xp,3000);
assert.throws(()=>season.action(u,{action:'pass_claim',track:'premium',tier:1}),/관리자/);
assert.equal(season.action(u,{action:'pass_claim',track:'free',tier:10}).reward.coins,925);assert.equal(u.coins,925);assert.throws(()=>season.action(u,{action:'pass_claim',track:'free',tier:10}),/이미/);
let before=u.owned.length;season.action(u,{action:'pass_claim',track:'free',tier:20});assert.equal(u.owned.length,before+1);assert.equal(u.coins,950);const selected=ids.find(id=>!u.owned.includes(id));assert.throws(()=>season.action(u,{action:'pass_claim',track:'free',tier:30,hero:'pizza'}),/선택/);assert(!u.season.claimed.includes('free:30'));season.action(u,{action:'pass_claim',track:'free',tier:30,hero:selected});assert(u.owned.includes(selected));assert.equal(u.coins,975);
u=user();u.owned=[...ids];season.migrate(u);u.season.xp=3000;season.action(u,{action:'pass_claim',track:'free',tier:20});assert.equal(u.coins,525);season.action(u,{action:'pass_claim',track:'free',tier:30});assert.equal(u.coins,1550);S.grantPremium(u);season.action(u,{action:'pass_claim',track:'premium',tier:1});assert.equal(u.coins,1600);
u=user();season.action(u,{action:'attendance_claim'});assert.equal(u.coins,25);assert.throws(()=>season.action(u,{action:'attendance_claim'}),/이미/);u.attendance.lastDay='2000-01-01';season.action(u,{action:'attendance_claim'});assert.equal(u.owned.length,2);u.attendance.count=4;u.attendance.lastDay='2000-01-01';season.action(u,{action:'attendance_claim'});assert.equal(u.owned.length,3);
u=user();u.owned=[...ids];u.attendance={count:1,lastDay:null};season.action(u,{action:'attendance_claim'});assert.equal(u.coins,500);
u=user();assert.throws(()=>season.action(u,{action:'quest_claim',quest:'play'}),/먼저/);for(let i=0;i<3;i++)season.record(u,[{hero:ids[i]}],i===0);season.action(u,{action:'quest_claim',quest:'play'});season.action(u,{action:'quest_claim',quest:'win'});season.action(u,{action:'quest_claim',quest:'heroes'});assert.equal(u.coins,40);assert.equal(u.season.xp,50);assert.throws(()=>season.action(u,{action:'quest_claim',quest:'play'}),/이미/);u.daily.day='2000-01-01';season.migrate(u);assert.equal(u.daily.play,0);
const admin=user(P.ADMIN_TAG),recipient=user(),profiles=new Map([[admin.id,admin],[recipient.id,recipient]]);progress.migrate(admin);const gift={action:'admin_send',scope:'one',tag:recipient.tag,coins:10,heroes:['pizza'],premium:true,requestId:'v13-premium-gift'};assert.throws(()=>progress.action(recipient,gift,profiles),/관리자/);progress.action(admin,gift,profiles);const m=recipient.mail[0];progress.action(recipient,{action:'mail_claim',mailId:m.id},profiles);progress.action(recipient,{action:'mail_claim',mailId:m.id},profiles);assert.equal(recipient.coins,510);assert.equal(recipient.season.premium,true);
for(const h of E.HEROES){const s=E.create([h.id,'pizza']);s.manualUlt=[true,true];s.actors.forEach(a=>{a.atkTimer=Infinity;a.vx=a.vy=0;a.contact=999;a.ultTimer=.01;});E.tick(s,.02);assert.equal(s.actors[0].ultUses,0,h.id+' waits for input');s.actors[0].mute=1;assert(!E.useUltimate(s,0));s.actors[0].mute=0;assert(E.useUltimate(s,0),h.id+' can activate');assert.equal(s.actors[0].ultUses,1);assert(!E.useUltimate(s,0),h.id+' cannot spam');assert(s.actors[0].ultCooldown>0);}
assert.equal(E.useUltimate(null,0),false);
console.log('PASS Season 1: 60 wins/3000XP, exact 25/50 coins and milestones, missing heroes and fallbacks, daily/attendance claims, admin premium and duplicate compensation, all 27 manual ultimates');
