'use strict';
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),{EventEmitter}=require('node:events');
(async()=>{const root=path.join(__dirname,'..'),src=fs.readFileSync(path.join(root,'server.js'),'utf8');let listener;const pending=[];const ticks=[];const ctx={require(n){if(n==='node:http')return {createServer(fn){listener=fn;return {listen(){}}}};return n.startsWith('./')?require(path.join(root,n)):require(n)},__dirname:root,process:{env:{},on(){}},console:{log(){},error(){}},setTimeout(fn,ms){pending.push({fn,ms});return pending.length},clearTimeout(){},setInterval(fn,ms){ticks.push(fn);return {unref(){}}},clearInterval(){},Buffer,URL};vm.createContext(ctx);vm.runInContext(src.slice(0,src.indexOf('initStorage().then(')),ctx);ctx.db={query:async()=>({rows:[]})};vm.runInContext('dbPool=db;profiles.clear()',ctx);const state=vm.runInContext('({profiles,sessions,rooms,royales,migrate,matchStats,startCombat,action,royaleAction,CLAN_MISSIONS})',ctx);const users=['6E2C5BF4','ABCDEF12','ABCDEF13'].map((tag,i)=>state.migrate({id:'user'+i,secret:'secret'+i,tag,nick:'유저'+i,owned:['pizza','rico','moai'],coins:0,wins:0,losses:0,setupDone:true}));users.forEach(u=>state.profiles.set(u.id,u));
async function request(m){return new Promise(resolve=>{const req=new EventEmitter();req.method='POST';req.url='/social';const res={writeHead(status){this.status=status},end(raw){resolve({status:this.status,...JSON.parse(raw)})}};listener(req,res);req.emit('data',JSON.stringify(m));req.emit('end')})}
const auth=i=>({id:users[i].id,secret:users[i].secret});let response=await request({action:'admin_send',...auth(1),scope:'all',coins:0,heroes:[],premium:true,requestId:'v13-security-premium'});assert.equal(response.status,400);await request({action:'admin_send',...auth(0),scope:'one',tag:users[1].tag,coins:0,heroes:['pizza'],premium:true,requestId:'v13-admin-premium'});const mail=users[1].mail[0];await Promise.all([request({action:'mail_claim',...auth(1),mailId:mail.id}),request({action:'mail_claim',...auth(1),mailId:mail.id})]);assert.equal(users[1].coins,500);assert(users[1].season.premium);
assert.equal((await request({action:'pass_claim',...auth(1),track:'free',tier:1})).status,400);users[1].season.xp=100;const claims=await Promise.all([request({action:'pass_claim',...auth(1),track:'free',tier:1}),request({action:'pass_claim',...auth(1),track:'free',tier:1})]);assert.deepEqual(claims.map(x=>x.status).sort(),[200,400]);assert.equal(users[1].coins,525);const check=await request({action:'get',...auth(1)});assert.equal(check.profile.seasonPass.tier,1);
const attendance=await Promise.all([request({action:'attendance_claim',...auth(1)}),request({action:'attendance_claim',...auth(1)})]);assert.deepEqual(attendance.map(x=>x.status).sort(),[200,400]);assert.equal(users[1].coins,550);
for(let i=1;i<3;i++)state.sessions.set('s'+i,{id:'s'+i,profile:users[i].id,side:i-1,stream:{write(){}},room:'testroom'});const s1=state.sessions.get('s1'),s2=state.sessions.get('s2'),room={id:'testroom',players:['s1','s2'],picks:['pizza','rico'],angles:[0,0],scores:[0,0],round:1,acks:new Set(),history:[[],[]]};state.rooms.set(room.id,room);state.startCombat(room);assert.equal(room.phase,'loading');assert.equal(room.sim.t,0);assert.throws(()=>state.action(s1,{action:'ultimate'}),/아직/);pending.find(x=>x.ms===0).fn();assert.equal(room.phase,'battle');room.sim.actors.forEach(a=>{a.ultTimer=0;a.atkTimer=Infinity;a.vx=a.vy=0;a.contact=99});ticks[ticks.length-1]();assert.equal(room.sim.actors[0].ultUses,0);state.action(s1,{action:'ultimate'});assert.equal(room.sim.actors[0].ultUses,1);assert.equal(room.sim.actors[1].ultUses,0);assert.throws(()=>state.action(s1,{action:'ultimate'}),/아직/);state.action(s2,{action:'ultimate'});assert.equal(room.sim.actors[1].ultUses,1);
const before=users[1].season.xp,normal={players:['s1','s2'],picks:room.picks,history:[[{hero:'pizza',won:true}],[]]};state.matchStats(normal,0);state.matchStats(normal,0);assert.equal(users[1].coins,560);assert.equal(users[1].season.xp,before+50);assert.equal(users[1].daily.play,1);const ff={players:['s1','s2'],picks:room.picks,history:normal.history};state.matchStats(ff,0,true);assert.equal(users[1].coins,570);assert.equal(users[1].season.xp,before+50);assert.equal(users[1].daily.play,1);assert.deepEqual(Array.from(state.CLAN_MISSIONS,x=>x.reward),[20,60,150]);
const r=require('../royale');let royal=r.create(users.map((u,i)=>({sid:'roy'+i,hero:i?'rico':'pizza',nick:u.nick})));royal.manualUlt=[true,true,true];royal.actors.forEach(a=>{a.ultTimer=0;a.atkTimer=Infinity});r.tick(royal,.05);assert(royal.actors.every(a=>a.ultUses===0));assert(r.useUltimate(royal,0));assert.equal(royal.actors[0].ultUses,1);
await vm.runInContext('dbSaveChain',ctx);console.log('PASS server: premium auth, simultaneous claims, instant combat start without in-battle loading, owned-side-only manual ultimate, royale manual, 10 coins + 50XP exactly once, no forfeit XP/daily progress, reduced club rewards');})().catch(e=>{console.error(e);process.exit(1)});
